### ISSUE TITLE
launching pgs_calc from AWS/Tower

### ISSUE THREAD

**Issue by atrigila** [PGScatalog/pgsc_calc#108]
### Description of the bug

Hi! First of all, thanks for developing this tool :)
I am having some issues using it in Nextflow Tower. I am launching the execution in AWS Batch and I am having the following error:

```
Command error:
  root: 2023-05-31 12:37:06 DEBUG    Verbose logging enabled
  pgscatalog_utils.download.download_scorefile: 2023-05-31 12:37:06 CRITICAL Downloading harmonized scoring file(s) in build: GRCh37.
  pgscatalog_utils.download.download_scorefile: 2023-05-31 12:37:06 DEBUG    --trait set, querying traits (including PGS for child terms)
  pgscatalog_utils.download.trait: 2023-05-31 12:37:06 DEBUG    Querying PGS Catalog with trait None
  urllib3.connectionpool: 2023-05-31 12:37:06 DEBUG    Starting new HTTPS connection (1): www.pgscatalog.org:443
  urllib3.connectionpool: 2023-05-31 12:37:06 DEBUG    https://www.pgscatalog.org:443 "GET /rest/trait/None?include_children=0 HTTP/1.1" 200 2
  pgscatalog_utils.download.trait: 2023-05-31 12:37:06 CRITICAL Bad response from PGS Catalog for EFO term: None
  Traceback (most recent call last):
    File "/venv/bin/download_scorefiles", line 8, in <module>
      sys.exit(download_scorefile())
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/download/download_scorefile.py", line 45, in download_scorefile
      pgs_lst = pgs_lst + [query_trait(x, pgsc_calc_info, args.efo_include_children) for x in args.efo]
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/download/download_scorefile.py", line 45, in <listcomp>
      pgs_lst = pgs_lst + [query_trait(x, pgsc_calc_info, args.efo_include_children) for x in args.efo]
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/download/trait.py", line 16, in query_trait
      raise Exception
  Exception
  [90m12:37PM[0m [32mINF[0m shutdown filesystem start
  [90m12:37PM[0m [32mINF[0m shutdown filesystem done
```
I am attaching the log here. 
I do not have these issues when I launch the pipeline locally, even when reading from S3. I tried running the pipeline in Tower a few times and I also sometimes have another error:

```
Caused by:
  Unexpected path for Fusion script launcher: /my_organization-nextflow/scratch/4P41T4npINVslW/genomes/A019710-S/ALL
 -- Check 'nf-4P41T4npINVslW.log' file for details
```

Please let me know if this second error is more Tower/configuration-related and if it's better to ask in their Slack, or if I should also add the logs here. Thank you!

### Command used and terminal output

```console
nextflow run 'https://github.com/PGScatalog/pgsc_calc' \
		 -name own_samples_s3 \
		 -params-file 'https://api.tower.nf/ephemeral/XXX.json' \
		 -with-tower \
		 -r v1.3.2

Params (attaching file with full configuration)
```

### Relevant files

[configuration_nextflow.txt](https://github.com/PGScatalog/pgsc_calc/files/11614362/configuration_nextflow.txt)
[log_file_31052023.log](https://github.com/PGScatalog/pgsc_calc/files/11614384/log_file_31052023.log)
[console_output.txt](https://github.com/PGScatalog/pgsc_calc/files/11614405/console_output.txt)

### System information

-     Nextflow version: 23.04.1 build 5866
-     Hardware: Cloud
-     Executor: awsbatch
-     Container engine: Docker
-     Version of pgsc_calc: 1.3.2

**Comment by nebfield** [comment]
Thanks for reporting this bug 😄 

Luckily I've had this problem before with nextflow tower. Try checking the parameters section of a failed job in tower to see if the scoring file parameters have been transformed from `null` into `None`:

![image](https://github.com/PGScatalog/pgsc_calc/assets/11425618/f2db8733-a054-4916-94b9-15c417e37c02)

`pgsc_calc` expects scoring file parameters (`trait_efo`, `pgp_id`, and `pgs_id`) to be `null` (the default) or a valid accession. `None` isn't a valid accession so things go wrong 😅 

Try overwriting the scoring file parameters manually in tower:

![image](https://github.com/PGScatalog/pgsc_calc/assets/11425618/d40a65f1-8b53-4bf1-8858-faf1d5be46a4)

Don't forget to include some scoring file accessions in this section e.g. `pgs_id: "PGS001229,PGS000802"`

It might be worth submitting a bug report to the nf-tower developers too.

I hope that fixes your problem!

**Comment by Fiwx** [comment]
@atrigila Did you ever get pgsc_calc working in AWS Batch?

**Comment by nebfield** [comment]
I've been running some tests with [google cloud batch](https://cloud.google.com/batch?hl=en) and the test profile is failing (a problem using cloud storage working directory). You'll probably experience similar problems on AWS.

Once I figure out what's wrong, we'll do a new release and set up some documentation for cloud execution.

**Comment by crohrheritas** [comment]
Did you find a fix for this issue?

**Comment by nebfield** [comment]
Sorry for the very late reply @atrigila 😅 

I launched an instance of the workflow from seqera platform with the google cloud batch executor and it worked OK. I used the test profile.

We've done a lot of work with recent releases to fix some cloud storage issues which might have fixed the fusion FS problem reported originally. 

I'm going to close this issue but please feel free to open a new issue if you experience problems with seqera platform.

**Comment by nebfield** [comment]
Quick update: has been working OK for me on a few different large jobs. The only thing to be careful about is the samplesheet. The samplesheet should be in JSON format, like this:

```
[
    {
        "pheno": "gs://bucket/data/all_phase3.psam",
        "vcf_import_dosage": false,
        "variants": "gs://bucket/data/all_phase3.pvar.zst",
        "geno": "gs://bucket/data/all_phase3.pgen",
        "sampleset": "test",
        "chrom": null,
        "format": "pfile"
    }
]
```

(and `format` parameter needs to be set to JSON). I'll update the docs with better examples.
