### ISSUE TITLE
Improve efficiency of scoring

### ISSUE THREAD

**Issue by mglev1n** [PGScatalog/pgsc_calc#112]
### Description of feature

I noticed that when using genotype data that contains a large number of samples/variants (Eg. TOPMed imputed genotypes), the plink2 scoring step is quite prolonged. I think that performance could be improved by adding the `--error-on-freq-calc` argument to `plink2` in `plink2_score.nf`:

https://github.com/PGScatalog/pgsc_calc/blob/c42dd1dee7208ab2f58a726e83234f348f5ea37d/modules/local/plink2_score.nf#L40-L47

Plink spends a large amount of time calculating allele frequencies, but when the number of variants in the genotype file is much greater than the number of variants in the scoring file, a large amount of time is wasted on this operation that doesn't seem directly relevant to scoring. Passing the `--error-on-freq-calc` argument asserts that frequencies aren't used (which given the current use of `no-mean-imputation` is valid), and should considerably improve performance: <http://cog-genomics.org/plink/2.0/input#read_freq>

**Comment by smlmbrt** [comment]
@mglev1n - thanks for suggesting this! We had this on an older version of the scoring pipeline but will test re-implementing it here for the speed gain

**Comment by smlmbrt** [comment]
Turns out that --extract is a better way to do this (only loads data from scoring file variants)
