### ISSUE TITLE
Report backend improvements

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#134]
### Description of feature

Some things to improve building and updating the output report:

- [x] Use renv to capture dependencies [in a lock file](https://rstudio.github.io/renv/articles/renv.html) to improve stability / reproducibility (I'm manually building container images currently)

These won't affect the content of the report but instead change how the report is built

**Comment by smlmbrt** [comment]
I'd prefer to not make a package - I like that it's easy to see and edit the report in the repo

**Comment by smlmbrt** [comment]
Also we need to version the report environment, using dev causes problems for new runs of the pipeline: https://github.com/PGScatalog/pgsc_calc/blob/3b7ebcc2081406101d023e67d2ace10b1880a355/conf/modules.config#L61-L67
