### ISSUE TITLE
Extra QA for scoring

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgsc_calc#141]
### Description of feature

Add additional checks to make sure all variants in the scoring file have been calculated on the samples. Currently this check is only for test data, but it should run on real data to ensure the SUMs are always directly comparable across datasets). Related to #139

- [ ] Check .sscore.vars against scoring file variants to ensure that they have been calculated correctly.
- [ ] Update test profile to require scoring file combination and deduplication.

**Comment by smlmbrt** [comment]
In #244 we make sure that all scoring files have yielded results.

**Comment by DarioS** [comment]
Does "score correlation tests" refer to something like a heatmap? It would be nice to see one as standard in the HTML report.
![image](https://github.com/PGScatalog/pgsc_calc/assets/631218/4e2b1bd2-5530-471b-a665-b09b64deacf5)
This plot tell us whether newer PGS are genuinely novel or are more of the same and of dubious value.

**Comment by smlmbrt** [comment]
Specifically checking that the .vars file is identical to the variants in the scoring file using a diff command?

**Comment by smlmbrt** [comment]
> Does "score correlation tests" refer to something like a heatmap? It would be nice to see one as standard in the HTML report. ![image](https://private-user-images.githubusercontent.com/631218/316208228-4e2b1bd2-5530-471b-a665-b09b64deacf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODkzNjgsIm5iZiI6MTcxNDM4OTA2OCwicGF0aCI6Ii82MzEyMTgvMzE2MjA4MjI4LTRlMmIxYmQyLTU1MzAtNDcxYi1hNjY1LWIwOWI2NGRlYWNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxMTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2IwMDhmZTkxYTBlZWQ2MDJjNmIwNzU2NmY4YmFjMjM3YjU1OTU0MTdjMWQ2YTAzN2NkZDRjM2E5MDNlOGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BvYfMcufjGLkhmuAqRU4W55B4r_s302YqQI9ezXm8_k) This plot tell us whether newer PGS are genuinely novel or are more of the same and of dubious value.

No, this seems too related to custom analyses and not general use of the pipeline. It's also trivial to do by reading in the pgs file, pivoting wide, and running cor in R.

**Comment by smlmbrt** [comment]
Now added to `PLINK2_SCORE`:
https://github.com/PGScatalog/pgsc_calc/blob/96fbb2346978c12917d35dc68520a86a9f7b7cc0/modules/local/plink2_score.nf#L67-L75
