### ISSUE TITLE
2 CPU Requirement Not Stated in Get Started of Documentation

### ISSUE THREAD

**Issue by DarioS** [PGScatalog/pgsc_calc#157]
### Description of the bug

```
ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)'

Caused by:
  Process requirement exceeds available CPUs -- req: 2; avail: 1
```

Only appears in Section 4 Next Steps. Should appear near the top instead.

### Command used and terminal output

```console
N/A
```

### Relevant files

N/A

### System information

N/A

**Comment by smlmbrt** [comment]
Hi @DarioS - did you try setting the `--max_cpu 1` in the command? The pipeline doesn't explicitly require multiple CPUs (it will run slower without), it mostly has memory/RAM requirements for when the data become large. 

Additional docs in troubleshooting: https://pgsc-calc.readthedocs.io/en/latest/troubleshooting.html#the-workflow-isn-t-using-many-resources-e-g-ram-cpu

**Comment by DarioS** [comment]
Yes, or alternatively I used `ncpus=2` for PBS resource request.
