### ISSUE TITLE
Scoring precision

### ISSUE THREAD

**Issue by CristianRiccio** [PGScatalog/pgsc_calc#162]
### Description of the bug

PGS Calculator rounds effect weights and returns an imprecise PGS.

I have used the following scoring file:
#pgs_name=AF
#trait_reported=Atrial fibrillation
#genome_build=GRCh38
chr_name	chr_position	effect_allele	other_allele	effect_weight
22	20441888	T	C	-4.99737**1**e-05

The aggregated_scores.txt.gz file starts like this:
sampleset	IID	DENOM	PGS999999_1_SNPs_hmPOS_GRCh38_SUM	PGS999999_1_SNPs_hmPOS_GRCh38_AVG
XXX YYY1 2	-4.99737e-05	-2.498685e-05
XXX YYY2 2	-4.99737e-05	-2.498685e-05

The SUM is missing a decimal digit. Added over many round errors, this approximation leads to imprecise results.

### Command used and terminal output

```console
nextflow run pgscatalog/pgscalc -profile singularity --input samplesheet.csv --target_build GRCh38 --scorefile PGS999999_1_SNPs_hmPOS_GRCh38.txt --outdir PGS999999_1_SNPs/nextflow/
```

### Relevant files

[PGS999999_1_SNPs_hmPOS_GRCh38.txt](https://github.com/PGScatalog/pgsc_calc/files/12521209/PGS999999_1_SNPs_hmPOS_GRCh38.txt)

### System information

HPC
nextflow version 23.04.1.5867
GNU/Linux

**Comment by smlmbrt** [comment]
On investigation using v2.0.0-alpha.2 I can replicate the issue:
- `combine_scorefiles` leaves the weight untouched (-4.997371e-05)
- `match_variants` / `match_combined` returns a scorefile with the variant not in scientific notation, but untouched precision (-0.00004997371)
- plink2 score seems to be the problem (`HGDP_ALL_additive_0.sscore.zst`): 
    ```
    #IID    population      latitude        longitude       region  ALLELE_CT       DENOM   NAMED_ALLELE_DOSAGE_SUM pgs_af_AVG      pgs_af_SUM
    HGDP00001       Brahui  30.5    66.5    CENTRAL_SOUTH_ASIA      2       2       1       -2.49869e-05    -4.99737e-05
    HGDP00003       Brahui  30.5    66.5    CENTRAL_SOUTH_ASIA      2       2       0       0       0
    HGDP00005       Brahui  30.5    66.5    CENTRAL_SOUTH_ASIA      2       2       1       -2.49869e-05    -4.99737e-05
    HGDP00007       Brahui  30.5    66.5    CENTRAL_SOUTH_ASIA      2       2       2       -4.99737e-05    -9.99474e-05
    ```
- This doesn't seem to change the plink2 score output if you make a scoring file with the original weight (-4.997371e-05)

**Comment by smlmbrt** [comment]
Reported in https://github.com/chrchang/plink-ng/issues/248

**Comment by smlmbrt** [comment]
From https://github.com/chrchang/plink-ng/issues/248:
> Not a bug. Practically all plink2 commands print floating-point values to 6 decimal places; printing to "full precision" would inflate file sizes while adding negligible scientific value. The source code is available if you actually need more digits of precision to be printed here.

I think then we should add this information to the documentation. There isn't a loss of precision in the calculation, only in the printing of the result so there won't be a pervasive rounding error that will bias the SUM, more just a loss of precision in the output.
