### ISSUE TITLE
combine_scorefiles: command not found??

### ISSUE THREAD

**Issue by XiaoyuQian829** [PGScatalog/pgsc_calc#163]
### Description of the bug

Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)` terminated with an error exit status (127)

Command executed:

  combine_scorefiles -s OPGS002658.txt             -t GRCh37             -o scorefiles.txt.gz             -l log_scorefiles.json             -v
  
  cat <<-END_VERSIONS > versions.yml
  COMBINE_SCOREFILES:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: combine_scorefiles: command not found

### Command used and terminal output

```console
${softwares}"/nextflow" run pgscatalog/pgsc_calc -r v1.3.2\
    -profile conda \
    --target_build GRCh37 \
    --input ${data}"/samplesheet.csv" \
    --parallel \
    --scorefile ${data}"/Olink/OPGS002658.txt"
    -c my_custom.config
```

**Comment by smlmbrt** [comment]
@XiaoyuQian829, does the same thing happen when you run with `-r v2.0.0-alpha.1`? That should update the pipeline to the latest images that work

**Comment by nebfield** [comment]
Does the same issue happen when you try the docker or singularity profiles? We try to discourage the use of the conda profile, it's only useful for situations when you can't install docker or singularity.

**Comment by XiaoyuQian829** [comment]
>

**Comment by XiaoyuQian829** [comment]
> @XiaoyuQian829, does the same thing happen when you run with `-r v2.0.0-alpha.1`? That should update the pipeline to the latest images that work

It is solved in the way you mentioned, thank you!
