### ISSUE TITLE
ERROR nextflow.Nextflow - ERROR: No results report written!

### ISSUE THREAD

**Issue by frahimov** [PGScatalog/pgsc_calc#172]
### Description of the bug

The pipeline seems to fail at the last step, writing a report. But I cannot figure out from the log file what exactly goes wrong. The analysis was run on an HPC with SUSE OS. Thank you

### Command used and terminal output

```console
nextflow run pgscatalog/pgsc_calc -profile docker --input samplesheet.csv --target_build GRCh37 --min_overlap 0.0 --pgs_id PGS000754
```

### Relevant files

[nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/12629410/nextflow.log)

### System information

HPC with SUSE OS

**Comment by smlmbrt** [comment]
By any chance do you have underscores or periods in your sampleset names in the samplesheet? I ran into that problem and pushed a check that will be in the next release. Until then (docs [1](https://pgsc-calc.readthedocs.io/en/dev/how-to/samplesheet.html#setup-samplesheet) [2](https://pgsc-calc.readthedocs.io/en/dev/reference/input.html)): 

> sampleset: A text string (no spaces, or reserved characters [ ‘.’ or ‘_’ ]) referring to the name of a [target dataset](https://pgsc-calc.readthedocs.io/en/dev/glossary.html#term-target-dataset) of genotyping data containing at least one sample/individual (however cohort datasets will often contain many individuals with combined genotyped/imputed data).

**Comment by frahimov** [comment]
Yes, I do. My sampleset names are like this "sle_imm_profile". Should I remove the underscores?
