### ISSUE TITLE
Handle non-autosomal chromosomes (X, Y, mtDNA)

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgsc_calc#20]
First it fails INPUT_CHECK Need to adapt to accommodate sex chromosomes (in text) and not just autosomes:
https://github.com/PGScatalog/pgsc_calc/blob/6f3f04296d89d6d42e6ea345dcdbe1f1eefcae3e/assets/schema_k8s.json#L21-L26

- Perhaps a list of accepted values and then maybe we recode 23 -> X?
- Also requires adapting `bin/match_variants.py` because it usually assumes chr is an integer and not categorical

**Comment by nebfield** [comment]
2e448705c40cdc1eb7ae2145d2f0e243f2499782

fixing the schema is on my list :smile:
