### ISSUE TITLE
missing deg2_phase3.king.cutoff.out.id file

### ISSUE THREAD

**Issue by frahimov** [PGScatalog/pgsc_calc#224]
### Description of the bug

Hello, I am getting an error when I run the pipeline with --run_ancestry.
tar: deg2_phase3.king.cutoff.out.id: Not found in archive
The error seems to occur because of the missing deg2_phase3.king.cutoff.out.id file in both "pgsc_1000G_v1.tar.zst" and "pgsc_HGDP+1kGP_v1.tar.zst" archives.
Here is the content of the pgsc_1000G_v1.tar.zst archive:
checksums.txt
GRCh37_1000G_ALL.pgen
GRCh37_1000G_ALL.psam
GRCh37_1000G_ALL.pvar.zst
GRCh37_1000G.king.cutoff.out.id
GRCh38_1000G_ALL.pgen
GRCh38_1000G_ALL.psam
GRCh38_1000G_ALL.pvar.zst
GRCh38_1000G.king.cutoff.out.id
meta.txt

Thank you

### Command used and terminal output

```console
#! /bin/bash
nextflow run pgscatalog/pgsc_calc \
        -profile docker \
        --input samplesheet_plink.csv \
        --target_build GRCh37 \
        --pgs_id PGS000754,PGS000196,PGS003755,PGS003756,PGS000771,PGS000772,PGS000328,PGS000803,PGS003757 \
        --min_overlap 0.70 \
        --run_ancestry /homes/rahimfx1/projects/immunology/sle/ttid_imm_profil_pgs/pgsc_1000G_v1.tar.zst \
        --parallel -c my_custom.config \
        --outdir /homes/rahimfx1/projects/immunology/sle/ttid_imm_profil_pgs/PGS_norm_1000G
```

**Comment by smlmbrt** [comment]
@frahimov are you using the latest version of the pipeline? Versions `>v2.0.0-alpha.3` should not have this error as they use the `GRCh3#_[ref].king.cutoff.out.id` file naming convention. This error should fix itself if you update the code by adding `-latest` to the nextflow command.

**Comment by frahimov** [comment]
Yes, nextflow was running an older version of the pipeline (v2.0.0-alpha.2). I was not aware of the _-latest_ flag. It worked now. Thank you very much for the tip!

**Comment by smlmbrt** [comment]
I'm glad that fixed it! You can also specify specific branches or tagged releases using the revision flag (`-r [release/branch]`).
