### ISSUE TITLE
Error 139 when running test profile on HPC

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#230]
Hi there, sorry for opening this again. I'm running into the same error when running the test command.

I've just installed pgsc calc for the first time in a new hpc server and am still testing.

- nextflow command: 
nextflow run pgscatalog/pgsc_calc -profile test,conda

- pgsc version: 
not sure how to check that, I would assume the latest

- I'm running the code on an HPC cluster

- error code:

```
> executor >  local (3)
> executor >  local (3)
> executor >  local (3)
> [58/dc6cbc] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [ 50%] 1 of 2, failed: 1..
> [31/715593] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCO... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWA... -
> [8e/49aa70] NOTE: Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139) -- Execution is retried (1)
> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   139
> 
> Command output:
>   (empty)
> 
> Command error:
>   OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
> executor >  local (3)
> [58/dc6cbc] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 2 of 2, failed: 2..
> [31/715593] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCO... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWA... -
> [8e/49aa70] NOTE: Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139) -- Execution is retried (1)
> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   139
> 
> Command output:
>   (empty)
> 
> Command error:
>   OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
> executor >  local (3)
> [58/dc6cbc] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 2 of 2, failed: 2..
> [31/715593] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCO... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWA... -
> [8e/49aa70] NOTE: Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139) -- Execution is retried (1)
> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   139
> 
> Command output:
>   (empty)
> 
> Command error:
>   OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   .command.run: fork: retry: Resource temporarily unavailable
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Assuming input samplesheet is a symlinked file in a nextflow working directory
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Following symlink and attempting to resolve path relative to input file
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Resolving paths relative to: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/assets/examples
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Assuming input samplesheet is a symlinked file in a nextflow working directory
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Following symlink and attempting to resolve path relative to input file
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Resolving paths relative to: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/assets/examples
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Assuming input samplesheet is a symlinked file in a nextflow working directory
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Following symlink and attempting to resolve path relative to input file
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Resolving paths relative to: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/assets/examples
>   .command.sh: line 2: 102687 Segmentation fault      samplesheet_to_json samplesheet.csv out.json
> 
> Work dir:
>   /hpc/users/gomesp04/work/58/dc6cbc5529e89e3dfc23a460d7de3a
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: Matching subworkflow failed
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: No results report written!
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: No scores calculated!
> 
>  -- Check '.nextflow.log' file for details
```

Thank you for your help!

_Originally posted by @pecko-g in https://github.com/PGScatalog/pgsc_calc/issues/76#issuecomment-1900167200_

**Comment by nebfield** [comment]
@pecko-g I opened a new issue for your problem to help us keep track of things 😄 

I think this is caused by a problem with your HPC set up. Are you running the test profile in an interactive job? See 
https://stackoverflow.com/a/54746150 

I'd recommend either:

* Submitting the test profile in a batch job or
* Asking your cluster admins for some help. They'll have put some restrictions in place, and might be happy to relax them.

Also, the singularity profile is the best option if your HPC supports it.

**Comment by nebfield** [comment]
I think you might need some support from your HPC sysadmins. 

Singularity shouldn't be building sandboxes:

```
 INFO: Converting SIF file to temporary sandbox...
``` 

When I run the workflow on other clusters this doesn't happen, because the singularity installation on these clusters is built with `setuid` support. This isn't something you can fix or figure out by yourself - hopefully your sysadmins can help 

I suggest running [nextflow as a batch job](https://www.nextflow.io/blog/2021/5_tips_for_hpc_users.html) using the conda profile as a temporary workaround (see tip 2, interactive jobs can cause problems).

**Comment by pecko-g** [comment]
Hi Benjamin,

thank you again for your help. I tried your suggestion of running a batch job and I also tried running interactive jobs, but I am still getting the same errors unfortunately.

The HPC support team suggested I run the pipeline replacing singularity with apptainer, when I did that, a different error was generated:

> executor >  local (2)
> [fd/40ba7a] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv) [100%] 1 of 1, failed: 1 ✘
> [9c/aee7ef] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)             [  0%] 0 of 1
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM              -
> executor >  local (2)
> [fd/40ba7a] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv) [100%] 1 of 1, failed: 1 ✘
> [9c/aee7ef] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)             [  0%] 0 of 1
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM              -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR             -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF                     -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS                           -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE                            -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE                       -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE                    -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT                            -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS                           -
> Execution cancelled -- Finishing pending tasks before exit
> Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   1
> 
> Command output:
>   INFO   : A system administrator may need to enable user namespaces, install
>   INFO   :   apptainer-suid, or compile with ./mconfig --with-suid
> 
> Command error:
>   INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
>   INFO   : A system administrator may need to enable user namespaces, install
>   ERROR  : Failed to create user namespace: user namespace disabled
>   INFO   :   apptainer-suid, or compile with ./mconfig --with-suid
> 
> Work dir:
>   /hpc/users/gomesp04/work/fd/40ba7aa4be4a9065e2e712eb26c9aa
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
> 
> 
> ERROR: No scores calculated!
> 
> 
> ERROR: No results report written!
> 
> 
> ERROR: Matching subworkflow failed

From the "namespaces" text, I suppose it has still something to do with the permissions in the cluster, so maybe not necessarily the pipeline itself.


Other than that, I tried running the pipeline with conda as well. There too an error is being generated:

> executor >  local (7)
> executor >  local (7)
> executor >  local (7)
> executor >  local (7)
> [52/4828d9] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)                         [100%] 1 of 1 ✔
> [9d/f0a18c] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                                     [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                                      -
> [skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR (cineca chromosome 22)              [100%] 1 of 1, stored: 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF                                             -
> [b4/885a5e] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS (cineca chromosome 22)                            [100%] 1 of 1 ✔
> [6a/2f1e91] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE (cineca)                                           [100%] 1 of 1 ✔
> [f1/0256a6] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE (cineca chromosome 22 effect type additive 0) [100%] 1 of 1 ✔
> [80/98f043] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE (cineca)                                   [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT                                                    -
> [5f/eda0e2] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS (1)                                               [100%] 1 of 1 ✔
> Creating env using conda: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/environments/report/environment.yml [cache /hpc/users/gomesp04/work/conda/report-3a0c38b9e1df3a8b8c85da7617f9131b]
> 
> Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT (cineca)'
> 
> Caused by:
>   Failed to create Conda environment
>   command: conda env create --prefix /hpc/users/gomesp04/work/conda/report-3a0c38b9e1df3a8b8c85da7617f9131b --file /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/environments/report/environment.yml
>   status : 1
>   message:
>     ResolvePackageNotFound: 
>       - quarto=1.3.433
> 
> 
> 
> 
> ERROR: No results report written!
> 
> 
> -[pgscatalog/pgsc_calc] Pipeline completed with errors-


It also seems cluster related. I already contacted the support team with this new information, but wanted to let you know where I stand.

Thank you again for your help and patience.

**Comment by nebfield** [comment]
[This might be helpful for your support team](https://singularity-admindoc.readthedocs.io/en/latest/the_singularity_config_file.html#allow-setuid-boolean-default-yes ). Most Singularity instances installed on a HPC default to `YES`. It looks like your installation might be set differently.

> This parameter toggles the global ability to execute the SETUID (SUID) portion of the code if it exists. As mentioned earlier, if the SUID features are disabled, various Singularity features will not function (e.g. mounting of the Singularity image file format). You can however disable SUID support iff (if and only if) you do not need to use the default Singularity image file format and if your kernel supports user namespaces and you choose to use user namespaces.

**Comment by pecko-g** [comment]
Hi Benjamin,

we finally found a solution! The test run works if I run an interactive job and use singularity version 3.11.0. (at least that's the name of the version in the HPC environment). So far we had tried running version 3.12. (newest in cluster) and 3.10.

Thank you for your help!
