### ISSUE TITLE
samplesheet setup issues

### ISSUE THREAD

**Issue by brianfennessy** [PGScatalog/pgsc_calc#241]
Hi,
I am having trouble setting up my samplesheet, I keep getting errors and am confused what exactly I need to put under each column. Is "sampleset" the name of the genetic data file? You refer to it as the target dataset of genotyping data, which is my own data. For path_prefix, it should be set to the path of the target genomes. This is referring to the directory with my target dataset of genotyping data? I have it set up that way, but it doesn't run and I don't know why. Is there a way to troubleshoot this with you?
Best,
Brian

**Comment by smlmbrt** [comment]
Could you paste the rows of the samplesheet here so we can see? And perhaps the specific error?

**Comment by brianfennessy** [comment]
Hi Sam,
My samplesheet has just one row under the header for Chr1 and looks like this:
sampleset,path_prefix,chrom,format
imputed1kgGSAGDAchr01,/mypath/target/imputed1kgGSAGDAchr01,1,pfile

The directory /mypath/target/ contains the following files:
imputed1kgGSAGDAchr01.log
imputed1kgGSAGDAchr01.pgen
imputed1kgGSAGDAchr01.psam
imputed1kgGSAGDAchr01.pvar

Here is my code (using PGS000907 to troubleshoot):
nextflow run pgscatalog/pgsc_calc -profile singularity --input samplesheet.csv --target_build GRCh37 --pgs_id PGS000907

I'm running on nextflow v22.10.7 and singularity v3.11.0. I have gotten different error messages, sometimes I find after running the same line of code. Here is an example:
Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name ghcr.io-pgscatalog-pgscatalog_utils-v0.4.3-singularity.img.pulling.1707884201997 oras://ghcr.io/pgscatalog/pgscatalog_utils:v0.4.3-singularity > /dev/null
  status : 2
  message:
    INFO:    Using cached SIF image
    runtime/cgo: pthread_create failed: Resource temporarily unavailable
    SIGABRT: abort
    PC=0x7ff3f9c80387 m=5 sigcode=18446744073709551610


I also see this warning, on the first line to pop up after running my code:
WARN: Can't read history file: .nextflow/history

**Comment by nebfield** [comment]
Your samplesheet looks OK. It seems like there's a problem with launching singularity containers on your computer.

What kind of environment are you trying to run the workflow on? Is it a HPC? One way of testing if singularity is working correctly on your computer would be to run:

```
$ singularity shell oras://ghcr.io/pgscatalog/pgscatalog_utils:v0.4.3-singularity
$ samplesheet_to_json --help
usage: samplesheet_to_json [-h] [-v] FILE_IN FILE_OUT

Convert pgscatalog/pgsc_calc samplesheet file to JSON and check its contents.
...
```

I'd also suggest trying other profiles like docker or conda if possible to see if the problem persists.

**Comment by brianfennessy** [comment]
Thank you, yes it is HPC. I think I solved that issue due to the particular node I was working on. Singularity does output the code you had above :) 

The SNP ID in my target data is coded as chr:pos:a1:a2 (eg. 1:794332:G:A), while I believe it is an rsID in the scoring file from PGS catalogue, so it now stops at this step:
process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE (imputed1kgGSAGDAchr01)

The error shows:
Command error:
  root: 2024-02-14 14:05:12 DEBUG    Verbose logging enabled
  pgscatalog_utils.config: 2024-02-14 14:05:12 DEBUG    Using 2 threads to read CSVs
  pgscatalog_utils.config: 2024-02-14 14:05:12 DEBUG    polars threadpool size: 2
  pgscatalog_utils.match.read: 2024-02-14 14:05:12 DEBUG    Reading scorefile
  pgscatalog_utils.match.read: 2024-02-14 14:05:13 DEBUG    --chrom parameter not set, using all variants in scoring file
  pgscatalog_utils.match.preprocess: 2024-02-14 14:05:13 DEBUG    Complementing column effect_allele
  pgscatalog_utils.match.preprocess: 2024-02-14 14:05:13 DEBUG    Complementing column other_allele
  pgscatalog_utils.match.combine_matches: 2024-02-14 14:05:13 DEBUG    Reading matches
  pgscatalog_utils.match.combine_matches: 2024-02-14 14:05:13 DEBUG    Labelling match candidates
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling best match type (refalt > altref > ...)
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling duplicated best match: keeping first instance as best_match = True
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling multiple scoring file lines (accession/row_nr) that best_match to the same variant
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2024-02-14 14:05:13 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Labelling multiallelic matches with exclude flag
  pgscatalog_utils.match.label: 2024-02-14 14:05:13 DEBUG    Not excluding flipped matches
  pgscatalog_utils.match.combine_matches: 2024-02-14 14:05:13 INFO     Scoring files are valid (no duplicate variants found)
  pgscatalog_utils.match.filter: 2024-02-14 14:05:13 DEBUG    Filtering to best_match variants (with exclude flag = False)
  pgscatalog_utils.match.filter: 2024-02-14 14:05:13 DEBUG    Calculating overlap between target genome and scoring file
  pgscatalog_utils.match.filter: 2024-02-14 14:05:13 ERROR    Score PGS001229_hmPOS_GRCh37 fails minimum matching threshold (6.49% variants match)
  pgscatalog_utils.match.match_variants: 2024-02-14 14:05:13 CRITICAL Error: no target variants match any variants in scoring files

Would you say this is due to the way the SNPs are coded in my dataset?

**Comment by nebfield** [comment]
Looking at your sampleset name: `imputed1kgGSAGDAchr01` Are you running the workflow using only a single chromosome (chr01)?

If the target genomes are split across multiple chromosomes, each chromosome should have the same sampleset name (e.g. `imputed1kgGSAGDA`).

PGS001229 contains variants from lots of chromosomes. A 6.49% match rate against 1 chromosome is quite good (because variants from 20ish chromosomes can't be matched). The workflow throws errors with low match rates because a new score calculated using only a single chromosome isn't faithfully reproducing PGS001229.

When authors submit PGS that only contain rsids the PGS Catalog [runs a harmonisation process to provide scoring files in builds GRCh37 and GRCh38](https://www.pgscatalog.org/downloads/#hm_pos_fn). The workflow will automatically grab the correct data with genomic coordinates, so you shouldn't have to worry about variant ID coding.

**Comment by brianfennessy** [comment]
Ah problem solved!!! Yes, I was initially running the workflow on Chr01 only. After your response above, I added rows for all chromosomes to my samplesheet.csv file, and the pipeline ran with no errors, and I received results. Thank you very much for your help!
