### ISSUE TITLE
Run ancestry Extract Database exit code 2 

### ISSUE THREAD

**Issue by sounkou-bioinfo** [PGScatalog/pgsc_calc#261]
### Description of the bug

Hi all,
Thank you for this great tools. 
**Here is the description of my issue** 
I run the workflow without the ancestry projection module and it runs fine. But when adding the ancestry projection step, i get this error :

ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)` terminated with an error exit status (2)

Command executed:

  tar -xf pgsc_1000G_v1.tar.zst --wildcards "GRCh37*" meta.txt 2> /dev/null
  
  DB_VERSION=$(cat meta.txt)
  
  if [ "$DB_VERSION" != "v0.1" ]; then
    echo "Old reference database version detected, please redownload the latest version and try again"
    echo "See https://pgsc-calc.readthedocs.io/en/latest/how-to/ancestry.html"
    exit 1
  else
    echo "Database version good"
  fi
  
  cat <<-END_VERSIONS > versions.yml
  EXTRACT_DATABASE:
      zstd: $(zstd -V | grep -Eo 'v[0-9]\.[0-9]\.[0-9]+' )
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  cp: '.command.out' and '.command.out' are the same file
  cp: '.command.err' and '.command.err' are the same file
  cp: '.command.trace' and '.command.trace' are the same file

**Setup description**
Nexflow run with docker profile with outputs stored on a mounted NAS drive. Input in plink2 format

### Command used and terminal output

```console
nextflow run -resume -ansi-log false ${nextflowDir}/main.nf \
        -profile docker \
        --input ${SamplePref}_pgscalc_sheet.csv  \
        --target_build GRCh37 \
        --pgs_id "${PGSList}" \
        --outdir ${OutputDir} \
        --max_cpus ${CPUS} \
        --max_memory 16.0GB \
        --run_ancestry ${PGSRefZST}
```

### System information

pgsc_calc v2.0.0-alpha.4
OS : Centos 8
Nexflow version : 23.10.1
Executor : local
Container engine : Docker

**Comment by smlmbrt** [comment]
@sounkou-bioinfo could you try it with the other reference dataset and see if you give the same result? Also is the reference on your local computer or online?

**Comment by sounkou-bioinfo** [comment]
@smlmbrt Thank you for your reply.

I got the same output with the TGP+HGDP reference file too. Both were (re)downloaded locally. I too thought it was the database version issue but i check in the work directory and it was v0.1 in the meta. And the error does not look to be about the database version :
"
Command error:
cp: '.command.out' and '.command.out' are the same file
cp: '.command.err' and '.command.err' are the same file
cp: '.command.trace' and '.command.trace' are the same file
"
appears to be something about copying .command files, which is odd. i tried to ignore the error by adding errorStrategy 'ignore'  in the "extract database" process definition, but the parent subworkfow breaks because the exit code is not ignored at that level. 

Do you know a way to make the parent subworkflow ignore this exist code ?

**Comment by smlmbrt** [comment]
I think something is happening where it's not extracting those files (maybe because they're not mounted correctly). We are currently working on a release that fixes some of these issues (hopefully published early next week). If you search around the issues about docker problems you might get some ideas about how to fix before then.

**Comment by sounkou-bioinfo** [comment]
@smlmbrt  the files are extracted, including the meta.txt file and the DB version info in it. I will be looking forward to the new release to see if that fixes the issue

**Comment by smlmbrt** [comment]
@sounkou-bioinfo it's worth trying the new release now to see if it fixes your problem.

**Comment by dpelegri** [comment]
Hi all,

Thank you for this great tools.

I have the same error reported by @sounkou-bioinfo  

```
-[pgscatalog/pgsc_calc] Pipeline completed with errors-
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)` terminated with an error exit status (2)

Command executed:

  tar -xf pgsc_1000G_v1.tar.zst --wildcards "GRCh37*" meta.txt 2> /dev/null

  DB_VERSION=$(cat meta.txt)

  if [ "$DB_VERSION" != "v0.1" ]; then
    echo "Old reference database version detected, please redownload the latest version and try again"
    echo "See https://pgsc-calc.readthedocs.io/en/latest/how-to/ancestry.html"
    exit 1
  else
    echo "Database version good"
  fi

  cat <<-END_VERSIONS > versions.yml
  EXTRACT_DATABASE:
      zstd: $(zstd -V | grep -Eo 'v[0-9]\.[0-9]\.[0-9]+' )
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  cp: '.command.out' and '.command.out' are the same file
  cp: '.command.err' and '.command.err' are the same file
  cp: '.command.trace' and '.command.trace' are the same file

Work dir:
  /scratch/dpelegri/pgsc_calc/work/fe/2b3cf51f021cade50b6fd11e9f4b6a

```

I'm using the 

 **pgscatalog/pgsc_calc v2.0.0-beta.3-g9bd9c43**


but instead of using docker I'm using conda , the command I run is:

```
nextflow run pgscatalog/pgsc_calc \
        -profile conda \
        --input ${SSDIR}Samplesheet_liver.csv \
        --target_build GRCh37 \
        --pgs_id ${PGS_LIST} \
        --run_ancestry ${PGS_ANC_ZST} \
        --outdir ${OUTDIR}
```
