### ISSUE TITLE
ERROR ~ Cannot find latest version of nf-validation plugin

### ISSUE THREAD

**Issue by Linlin1213a** [PGScatalog/pgsc_calc#268]
### Description of the bug

Hello, I want to use pgsc_calc to compute PGS, but I don't have the code base for it. Following the tutorial, I successfully installed nextflow and Docker. After Docker was configured, I ran the test profile on WSL2, but the following problems occurred: WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
Launching `https://github.com/pgscatalog/pgsc_calc` [trusting_darwin] DSL2 - revision: 8bdf287d55 [main]
ERROR ~ Cannot find latest version of nf-validation plugin.

### Command used and terminal output

```console
~$ nextflow run pgscatalog/pgsc_calc -profile test,docker
N E X T F L O W  ~  version 23.10.1
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
Launching `https://github.com/pgscatalog/pgsc_calc` [trusting_darwin] DSL2 - revision: 8bdf287d55 [main]
ERROR ~ Cannot find latest version of nf-validation plugin

 -- Check script '.nextflow/assets/pgscatalog/pgsc_calc/./workflows/pgsc_calc.nf' at line: 7 or see '.nextflow.log' file for more details
```

### System information

Nextflow version 23.10.1
Desktop
Docker
wsl2 
ubuntu

**Comment by nebfield** [comment]
The problem is being caused by:

```
ERROR ~ Cannot find latest version of nf-validation plugin
```

I think this is a problem with your local environment. These plugins should be automatically installed by nextflow.

Are you able to manually run:

```
$ nextflow plugin install nf-validation
$ nextflow plugin install nf-tower
```

And try again?

**Comment by Linlin1213a** [comment]
I am very happy to see your reply. I tried your code but it still didn't work. After checking, I found that it was the problem of network Settings. Thank you very much.
