### ISSUE TITLE
Invalid format: null ERROR ~ ERROR: Matching subworkflow failed

### ISSUE THREAD

**Issue by llgg2024** [PGScatalog/pgsc_calc#285]
### Description of the bug

I am an external user on a server and I can run the test profile . Without cloning your pipeline, while running with my own data, I got a problem: 
Invalid format: null
ERROR ~ ERROR: Matching subworkflow failed

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No scores calculated!

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No results report written!

 -- Check '.nextflow.log' file for details

Another user(an internal user) on the same server(we are in the same group according to groups) has used your pipeline since last year. He could run the pipeline successfully with the same code(I put all the code in a .sh file), however, he has a problem running the pipeline directly on his account: nextflow run pgscatalog/pgsc_calc --version
Nextflow 23.10.1 is available - Please consider updating your version to it
ERROR ~ .nextflow/history.lock (No such file or directory)
 -- Check '.nextflow.log' file for details
Somehow, I have not yet understood why.

After the hint of the solved problem #151, I cloned your pipeline and launched it directly as a command line: nextflow run main.nf -profile singularity --input xxxxx/samplesheet.csv --target_build GRCh38 --pgs_id PGS000016 --outdir xxxx/pgs_results

I used absolute paths for both directories and got the same errors described above. I checked the code, the error is from match.nf. Unfortunately, I do not have any clue how to debug.  I can use up to 64 CPUs. Could you please guide me through this puzzle? Thank you very much in advance!

### Command used and terminal output

```console
command in .sh file: 

#!/bin/bash 
modulesld
ml purge
ml load nextflow/23.10.0
ml load apptainer/1.2.4

nextflow run pgscatalog/pgsc_calc \
     -profile singularity \
     --input /cluster/xxxx/samplesheet.csv \
     --target_build GRCh38 --pgs_id PGS000016 \
     --outdir /cluster/xxxx/pgs_results 


terminal output:
Loading nextflow/23.10.0
  Loading requirement: java/17.0.9
Nextflow 23.10.1 is available - Please consider updating your version to it
N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/pgscatalog/pgsc_calc` [furious_stonebraker] DSL2 - revision: 8bdf287d55 [main]
WARN: Access to undefined parameter `monochromeLogs` -- Initialise it to a default value eg. `params.monochromeLogs = some_value`


------------------------------------------------------
  pgscatalog/pgsc_calc v2.0.0-alpha.5-g8bdf287
------------------------------------------------------
Core Nextflow options
  revision          : main
  runName           : furious_stonebraker
  containerEngine   : singularity
  launchDir         : /cluster/home/lguo
  workDir           : /cluster/home/lguo/work
  projectDir        : /cluster/home/lguo/.nextflow/assets/pgscatalog/pgsc_calc
  userName          : lguo
  profile           : singularity
  configFiles       : 

Input/output options
  input             : /cluster/home/lguo/samplesheet.csv
  pgs_id            : PGS000016
  outdir            : /cluster/storage/data/GWAS_HCHS/run_analyses/lguo/pgs_results

Reference options
  ref_samplesheet   : /cluster/home/lguo/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/reference.csv
  ld_grch37         : /cluster/home/lguo/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg19-GRCh37.txt
  ld_grch38         : /cluster/home/lguo/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg38-GRCh38.txt
  ancestry_checksums: /cluster/home/lguo/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/checksums.txt

Compatibility options
  target_build      : GRCh38

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use pgscatalog/pgsc_calc for your analysis please cite:

* The Polygenic Score Catalog
  https://doi.org/10.1038/s41588-021-00783-5

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/pgscatalog/pgsc_calc/blob/master/CITATIONS.md

[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES               -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES    -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABEL... -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF        -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS              -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE               -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE          -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE       -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT               -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS              -
Invalid format: null
ERROR ~ ERROR: Matching subworkflow failed

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No scores calculated!

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No results report written!

 -- Check '.nextflow.log' file for details
```

### Relevant files

[.nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/15076014/default.nextflow.log)

### System information

N E X T F L O W  ~  version 23.10.0
pgscatalog/pgsc_calc v2.0.0-alpha.5
containerEngine   : singularity
Excutor: slurm
Hardware: HPC
OS: Linux master 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC   x86_64 x86_64 x86_64 GNU/Linux

**Comment by llgg2024** [comment]
I got some tips from the previously solved issues, tried with different commands, and got the same problem. 

1. changed singularity to apptainer: I could run the test successfully with both apptainer and singularity, however, I failed with my data with both.
2. I downloaded the score file from the pgs catalog, and the reference file, and ran the pipeline locally, I got the same problem with apptainer or singularity: 
nextflow run pgsc_calc/main.nf -profile apptainer --input /cluster/xxxx/samplesheet.csv --target_build GRCh38 --scorefile /cluster/xxxxx/PGS000016.txt.gz --ref /cluster/xxxxxx/pgsc_calc_ref.sqlar

Somehow, I have no idea what I can do next... It would be great if someone could help me out.  Thanks!

**Comment by nebfield** [comment]
Could you upload an example of your samplesheet? (you can drag and drop files). I think there might be a problem parsing it.

Also, just FYI `--ref` has been deprecated in `v2` of the workflow. The reference database has been changed and the parameter has changed to `--run_ancestry` (so you don't need any sqlar files).

**Comment by llgg2024** [comment]
[samplesheet.csv](https://github.com/PGScatalog/pgsc_calc/files/15094579/samplesheet.csv)

As I mentioned previously(see below): another user ran my code(with the same samplesheet) successfully, so I suppose the samplesheet should be fine. 

Another user(an internal user) on the same server(we are in the same group according to groups) has used your pipeline since last year. He could run the pipeline successfully with the same code(I put all the code in a .sh file), however, he has a problem running the pipeline directly on his account: nextflow run pgscatalog/pgsc_calc --version
Nextflow 23.10.1 is available - Please consider updating your version to it
ERROR ~ .nextflow/history.lock (No such file or directory)
-- Check '.nextflow.log' file for details
Somehow, I have not yet understood why.

**Comment by llgg2024** [comment]
thanks @nebfield

**Comment by llgg2024** [comment]
Thank you for your quick reply!

Now I understand why it is not working. 

Before I move further, I have a question. As far as I understood the tools will be downloaded and run locally when I call the pipeline directly from my account. I assume that no genotype data needs to be uploaded to the cloud. Is it correct? 

The other user told me that he did not clone the pipeline. I am quite confused why he can call the old version with my bash code, in the meantime, he got a bug with:  nextflow run pgscatalog/pgsc_calc --version.

**Comment by smlmbrt** [comment]
Here's some instructions for how to run specific versions: https://pgsc-calc.readthedocs.io/en/latest/how-to/change_version.html

**Comment by llgg2024** [comment]
Thanks!
I assume that no genotype data needs to be uploaded to the cloud. Is it correct?

**Comment by smlmbrt** [comment]
There are no uploads, we designed pgsc_calc to be run in an airlocked environment (once you've predownloaded the software and scores) without internet access. The only possible external output might be if you set it to e-mail you a notification when it finishes? But that isn't default.

**Comment by llgg2024** [comment]
Great! Thank you very much!

**Comment by llgg2024** [comment]
I will debug further later and let you know whether it works with my data.

**Comment by llgg2024** [comment]
It worked. Thank you very much for your help indeed! @smlmbrt @nebfield 

It seems that the tools were downloaded during the first run, which is why the other user could run my code with his samplesheet for the V1, even though he did not specify the version. I thought that the newest version would be launched during each call.

**Comment by smlmbrt** [comment]
Glad it worked!
