### ISSUE TITLE
Add JSON samplesheet documentation

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#288]
### Description of feature

Samplesheet CSV parsing doesn't work well for use cases where genomes are in a cloud storage bucket (e.g. seqera platform / nextflow tower).

JSON samplesheets support this use case but we don't document the structure anywhere. Here's an example for inspiration:

```
[
    {
        "pheno": "gs://bucket/data/all_phase3.psam",
        "vcf_import_dosage": false,
        "variants": "gs://bucket/data/all_phase3.pvar.zst",
        "geno": "gs://bucket/data/all_phase3.pgen",
        "sampleset": "test",
        "chrom": null,
        "format": "pfile"
    }
]
```

**Comment by smlmbrt** [comment]
Related to #290?

**Comment by nebfield** [comment]
docs are now live in the dev branch 

b108b63829d436d3c908d28fe93f0959d4b3ea7f...28b639ac89f63b6b625acde96ff8f65e506d3cc2
