### ISSUE TITLE
Improve PGS Catalog compatibility

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#29]
- Support scores missing `other_allele` column :heavy_check_mark: 
- Support scores missing `chr_name` and `chr_position` (e.g. rsid only) :question:

**Comment by smlmbrt** [comment]
@ens-lgil could help with the second one (only rsID): we just need to use our mapping from ENSEMBL

**Comment by ens-lgil** [comment]
Could/should we use the Ensembl REST API for that ?
That would be the simplest solution, however this won't work for Scoring files with a lot of variants (as it is not designed for that).
The alternatives are the Ensembl VCF files or the Ensembl Perl API.

**Comment by smlmbrt** [comment]
For scores that are in the Catalog I'd assume they'd just download our pre-loaded positions (HmPOS). For scores that aren't in the Catalog we might need to write a module that does the rsID mapping using the VCFs?

**Comment by smlmbrt** [comment]
Versions of the scoring files with harmonized positions in builds GRCh37 and GRCh38 are now on the EBI FTP:
- See web documentation for more information: https://www.pgscatalog.org/downloads/
- Links to the scorings files are within the Score endpoints on the REST API, in the `ftp_harmonized_scoring_files` field: https://www.pgscatalog.org/rest/

**Comment by nebfield** [comment]
next release will automatically use harmonised positions 🎉
