### ISSUE TITLE
ERROR: No results report written!

### ISSUE THREAD

**Issue by frahimov** [PGScatalog/pgsc_calc#291]
### Description of the bug

My PGS run keeps failing. Initially I ran it with a custom score file. Then I tried --pgs_id, but still keeps failing. I use PLINK files with imputed genotype data. Any help or tips would be appreciated. Thank you. 
[nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/15249656/nextflow.log)

### Command used and terminal output

```console
#! /bin/bash
nextflow run pgscatalog/pgsc_calc \
        -profile docker \
        -latest \
        --input samplesheet_plink.csv \
        --target_build GRCh37 \
        --pgs_id PGS000754 \
        --min_overlap 0.10 \
        --parallel -c my_custom.config \
        --outdir /homes/rahimfx1/projects/immunology/reverse_translation/axspa/scripts/PGS_no_norm
```

### Relevant files

[my_custom.config.txt](https://github.com/PGScatalog/pgsc_calc/files/15249747/my_custom.config.txt)

[samplesheet_plink.csv](https://github.com/PGScatalog/pgsc_calc/files/15249748/samplesheet_plink.csv)

### System information

HPC, RedHat

**Comment by nebfield** [comment]
Could you please include some more information, like the complete terminal output and the `.nextflow.log` file in the directory where you run the workflow from

**Comment by frahimov** [comment]
I included the .nextflow.log file above. Here it is. [nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/15249757/nextflow.log)

**Comment by frahimov** [comment]
![Screenshot 2024-05-08 at 8 54 01 AM](https://github.com/PGScatalog/pgsc_calc/assets/25166708/ed2d9e66-e8f6-4304-b369-a847695746d8)

**Comment by frahimov** [comment]
I remember that issue :D 
I renamed the sampleset name, unfortunately I see an error again:

(base) rahimfx1@aurora:~/projects/immunology/reverse_translation/axspa/scripts> ./PGS_no_norm_copy.sh
N E X T F L O W  ~  version 23.04.3
Pulling pgscatalog/pgsc_calc ...
 Already-up-to-date
Launching `https://github.com/pgscatalog/pgsc_calc` [goofy_bartik] DSL2 - revision: 8bdf287d55 [main]
WARN: Access to undefined parameter `monochromeLogs` -- Initialise it to a default value eg. `params.monochromeLogs = some_value`


------------------------------------------------------
  pgscatalog/pgsc_calc v2.0.0-alpha.5-g8bdf287
------------------------------------------------------
Core Nextflow options
  revision          : main
  runName           : goofy_bartik
  containerEngine   : docker
  launchDir         : /homes/rahimfx1/projects/immunology/reverse_translation/axspa/scripts
  workDir           : /homes/rahimfx1/projects/immunology/reverse_translation/axspa/scripts/work
  projectDir        : /homes/rahimfx1/.nextflow/assets/pgscatalog/pgsc_calc
  userName          : rahimfx1
  profile           : docker
  configFiles       :

Input/output options
  input             : samplesheet_plink.csv
  pgs_id            : PGS000754
  outdir            : /homes/rahimfx1/projects/immunology/reverse_translation/axspa/scripts/PGS_no_norm

Reference options
  ref_samplesheet   : /homes/rahimfx1/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/reference.csv
  ld_grch37         : /homes/rahimfx1/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg19-GRCh37.txt
  ld_grch38         : /homes/rahimfx1/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg38-GRCh38.txt
  ancestry_checksums: /homes/rahimfx1/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/checksums.txt

Compatibility options
  target_build      : GRCh37

Matching options
  min_overlap       : 0.1

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use pgscatalog/pgsc_calc for your analysis please cite:

* The Polygenic Score Catalog
  https://doi.org/10.1038/s41588-021-00783-5

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/pgscatalog/pgsc_calc/blob/master/CITATIONS.md

executor >  local (2)
[7d/03021f] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000754, pgp_id:, trait_efo:]) [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES                                -
[de/93babe] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)   [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                            -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF                                    -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS                                          -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE                                      -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE                                   -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS                                          -
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)` terminated with an error exit status (6)

Command executed:

  plink2 \
      --threads 2 \
      --memory 16384 \
      --missing vcols=fmissdosage,fmiss \
      --new-id-max-allele-len 100 missing --allow-extra-chr \
      --set-all-var-ids '@:#:$r:$a' \
      --var-id-multi @:# \
      --bfile AxSpa_EUR.RefA2  \
executor >  local (2)
[7d/03021f] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000754, pgp_id:, trait_efo:]) [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES                                -
[de/93babe] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)   [100%] 1 of 1, failed: 1 ✘
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                            -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF                                    -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS                                          -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE                                      -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE                                   -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS                                          -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)` terminated with an error exit status (6)

Command executed:

  plink2 \
      --threads 2 \
      --memory 16384 \
      --missing vcols=fmissdosage,fmiss \
      --new-id-max-allele-len 100 missing --allow-extra-chr \
      --set-all-var-ids '@:#:$r:$a' \
      --var-id-multi @:# \
      --bfile AxSpa_EUR.RefA2  \
      --make-just-bim zs \
      --out GRCh37_axspaeur_ALL

executor >  local (2)
[7d/03021f] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000754, pgp_id:, trait_efo:]) [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES                                -
[de/93babe] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)   [100%] 1 of 1, failed: 1 ✘
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                            -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF                                    -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS                                          -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE                                      -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE                                   -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS                                          -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)` terminated with an error exit status (6)

Command executed:

  plink2 \
      --threads 2 \
      --memory 16384 \
      --missing vcols=fmissdosage,fmiss \
      --new-id-max-allele-len 100 missing --allow-extra-chr \
      --set-all-var-ids '@:#:$r:$a' \
      --var-id-multi @:# \
      --bfile AxSpa_EUR.RefA2  \
      --make-just-bim zs \
      --out GRCh37_axspaeur_ALL

  # cross platform (mac, linux) method of preserving symlinks
  cp -a AxSpa_EUR.RefA2.bed GRCh37_axspaeur_ALL.bed
  cp -a AxSpa_EUR.RefA2.fam GRCh37_axspaeur_ALL.fam
executor >  local (2)
[7d/03021f] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000754, pgp_id:, trait_efo:]) [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES                                -
[de/93babe] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)   [100%] 1 of 1, failed: 1 ✘
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                            -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF                                    -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS                                          -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE                                      -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE                                   -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT                                           -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS                                          -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (axspaeur chromosome ALL)` terminated with an error exit status (6)

Command executed:

  plink2 \
      --threads 2 \
      --memory 16384 \
      --missing vcols=fmissdosage,fmiss \
      --new-id-max-allele-len 100 missing --allow-extra-chr \
      --set-all-var-ids '@:#:$r:$a' \
      --var-id-multi @:# \
      --bfile AxSpa_EUR.RefA2  \
      --make-just-bim zs \
      --out GRCh37_axspaeur_ALL

  # cross platform (mac, linux) method of preserving symlinks
  cp -a AxSpa_EUR.RefA2.bed GRCh37_axspaeur_ALL.bed
  cp -a AxSpa_EUR.RefA2.fam GRCh37_axspaeur_ALL.fam
  gzip GRCh37_axspaeur_ALL.vmiss

  cat <<-END_VERSIONS > versions.yml
  PLINK2_RELABELBIM:
      plink2: $(plink2 --version 2>&1 | sed 's/^PLINK v//; s/ 64.*$//' )
  END_VERSIONS

Command exit status:
  6

Command output:
  PLINK v2.00a3.3 SSE4.2 (3 Jun 2022)            www.cog-genomics.org/plink/2.0/
  (C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
  Logging to GRCh37_axspaeur_ALL.log.
  Options in effect:
    --allow-extra-chr
    --bfile AxSpa_EUR.RefA2
    --make-just-bim zs
    --memory 16384
    --missing vcols=fmissdosage,fmiss
    --new-id-max-allele-len 100 missing
    --out GRCh37_axspaeur_ALL
    --set-all-var-ids @:#:$r:$a
    --threads 2
    --var-id-multi @:#

  Start time: Wed May  8 13:58:28 2024
  7616421 MiB RAM detected; reserving 16384 MiB for main workspace.
  Using up to 2 compute threads.
  379 samples (0 females, 0 males, 379 ambiguous; 379 founders) loaded from
  AxSpa_EUR.RefA2.fam.
  14232957 variants loaded from AxSpa_EUR.RefA2.bim.
  End time: Wed May  8 13:58:30 2024

Command error:
  Error: Unexpected PLINK 1 .bed file size (expected 1352130918 bytes).
  PLINK v2.00a3.3 SSE4.2 (3 Jun 2022)            www.cog-genomics.org/plink/2.0/
  (C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
  Logging to GRCh37_axspaeur_ALL.log.
  Options in effect:
    --allow-extra-chr
    --bfile AxSpa_EUR.RefA2
    --make-just-bim zs
    --memory 16384
    --missing vcols=fmissdosage,fmiss
    --new-id-max-allele-len 100 missing
    --out GRCh37_axspaeur_ALL
    --set-all-var-ids @:#:$r:$a
    --threads 2
    --var-id-multi @:#

  Start time: Wed May  8 13:58:28 2024
  7616421 MiB RAM detected; reserving 16384 MiB for main workspace.
  Using up to 2 compute threads.
  379 samples (0 females, 0 males, 379 ambiguous; 379 founders) loaded from
  AxSpa_EUR.RefA2.fam.
  14232957 variants loaded from AxSpa_EUR.RefA2.bim.
  End time: Wed May  8 13:58:30 2024
  cp: '.command.out' and '.command.out' are the same file
  cp: '.command.err' and '.command.err' are the same file
  cp: '.command.trace' and '.command.trace' are the same file

Work dir:
  /homes/rahimfx1/projects/immunology/reverse_translation/axspa/scripts/work/de/93babe6f4491b893cbffe8b66ad457

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: Matching subworkflow failed

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No scores calculated!

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No results report written!

 -- Check '.nextflow.log' file for details

**Comment by frahimov** [comment]
Actually, it worked with a different set of PLINK files! Thanks so much for your prompt response. I am going to try the run with the custom score file, and I hope I wont run into any issues.

**Comment by frahimov** [comment]
PGS run with a custom scores file worked too! Thanks again. I don't know why forgot about the sampleset naming.
