### ISSUE TITLE
COMBINE_MATCH failed even when the matching rate is above the threshold

### ISSUE THREAD

**Issue by zl2860** [PGScatalog/pgsc_calc#317]
**Hi! Thanks for providing such a wonderful tool. 
I have a series of custom score files downloaded from OMICSPRED to try on this tool, but I got confused when I saw the error message: All scores fail to meet match threshold 0.75. I assume that if there is at least one score passing the threshold, then the calculation would work** 

executor >  local (3)
[c4/c89f47] PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)     | 1 of 1 ✔
[skipped  ] PGS…LC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (Metabolon chromosome ALL) | 1 of 1, stored: 1 ✔
[-        ] PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR     -
[-        ] PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF             -
[15/73e533] PGS…SCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (Metabolon chromosome ALL) | 1 of 1 ✔
[24/f0adbd] PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE (Metabolon)        | 1 of 1, failed: 1 ✘
[-        ] PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE               -
[-        ] PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE            -
[-        ] PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT                    -
[-        ] PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS                   -

**However, even when I set --min-overlap to be 0.1, the error still occurs although some of the traits did have their matching rates above the threshold (see below).  I dont know why the scores passing the criteria failed to be combined.**
┌────────────┬────────────┬────────────┐
  │ accession  ┆ score_pass ┆ match_rate │
  │ ---        ┆ ---        ┆ ---        │
  │ cat        ┆ bool       ┆ f64        │
  ╞════════════╪════════════╪════════════╡
  │ OPGS003085 ┆ true       ┆ 0.764706   │
  │ OPGS003244 ┆ true       ┆ 0.333333   │
  │ OPGS003074 ┆ true       ┆ 0.769231   │
  │ OPGS002754 ┆ true       ┆ 0.52439    │
  │ OPGS003335 ┆ false      ┆ 0.0        │
  │ …          ┆ …          ┆ …          │
  │ OPGS003005 ┆ true       ┆ 0.1875     │
  │ OPGS003378 ┆ false      ┆ 0.0        │
  │ OPGS002707 ┆ true       ┆ 0.382199   │
  │ OPGS003407 ┆ false      ┆ 0.0        │
  │ OPGS003166 ┆ true       ┆ 0.833333   │
  └────────────┴────────────┴────────────┘

  pgscatalog.match.lib._match.log: 2024-06-17 14:40:34 DEBUG    Joining all match candidates against input scoring file
  sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  Traceback (most recent call last):
    File "/home/zongchaoliu/omicspred/SIT_data_for_prediction/work/conda/pgscatalog_utils-05f07a0c015260b9b43597a65cb4cca9/bin/pgscatalog-matchmerge", line 8, in <module>
      sys.exit(run_merge())
               ^^^^^^^^^^^
    File "/home/zongchaoliu/omicspred/SIT_data_for_prediction/work/conda/pgscatalog_utils-05f07a0c015260b9b43597a65cb4cca9/lib/python3.11/site-packages/pgscatalog/match/cli/merge_cli.py", line 70, in run_merge
      matchdf = write_matches(matchresults=matchresults, score_df=score_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/zongchaoliu/omicspred/SIT_data_for_prediction/work/conda/pgscatalog_utils-05f07a0c015260b9b43597a65cb4cca9/lib/python3.11/site-packages/pgscatalog/match/cli/_write.py", line 45, in write_matches
      raise e
    File "/home/zongchaoliu/omicspred/SIT_data_for_prediction/work/conda/pgscatalog_utils-05f07a0c015260b9b43597a65cb4cca9/lib/python3.11/site-packages/pgscatalog/match/cli/_write.py", line 33, in write_matches
      _ = matchresults.write_scorefiles(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/zongchaoliu/omicspred/SIT_data_for_prediction/work/conda/pgscatalog_utils-05f07a0c015260b9b43597a65cb4cca9/lib/python3.11/site-packages/pgscatalog/match/lib/matchresult.py", line 286, in write_scorefiles
      raise MatchRateError(
  pgscatalog.core.lib.pgsexceptions.MatchRateError: All scores fail to meet match threshold 0.1

Any way to solve this problem?

**Comment by nebfield** [comment]
Thanks for reporting the problem 😄  There's currently a bug in `v2.0.0-alpha.6 `where matching fails if one score fails.

If at least one score passes matching then the process is supposed to finish successfully. This behaviour is fixed in the development branch and we'll do a new release v2.0.0-beta some time this week. 

Two possible workarounds until we do a new release:

1) Try using the most recent stable release [v2.0.0-alpha.5](https://github.com/PGScatalog/pgsc_calc/releases/tag/v2.0.0-alpha.5) by using nextflow run `pgscatalog/pgsc_calc -r v2.0.0-alpha.5 ...`
2) Try the unreleased development branch `nextflow run pgscatalog/pgsc_calc -r dev`
