### ISSUE TITLE
Error - "Duplicated chromosome entries detected in samplesheet. Check your samplesheet." 

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [PGScatalog/pgsc_calc#338]
### Description of the bug

Hi, I have added path for multiple vcfs inside samplesheet.csv as input to the pipeline and kept `chr` column empty as recommended ("If the target genomic data file contains multiple chromosomes, leave empty."). 

However, I am keep on getting this error: `Duplicated chromosome entries detected in samplesheet. Check your samplesheet.`

Below is a section from my `samplesheet.csv` :
```
sampleset,path_prefix,chrom,format
proj1,/analysis/L12/vcf/L12, ,vcf
proj1,/analysis/L13/vcf/L13, ,vcf
proj1,/analysis/L14/vcf/L14, ,vcf
proj1,/analysis/L15/vcf/L15, ,vcf
```
- I also tried to use `-r v2.0.0-beta.1` but it says `Project pgscatalog/pgsc_calc contains uncommitted changes -- Cannot switch to revision: v2.0.0-beta.1`

Thanks.

### Command used and terminal output

```console
nextflow run pgscatalog/pgsc_calc -profile singularity \
    --input samplesheet.csv \
    --target_build GRCh38 \
    --pgs_id PGS001013,PGS001015 \
    --run_ancestry pgsc_HGDP+1kGP_v1.tar.zst \
    --outdir $PWD/results
```

### System information

Nextflow version: 23.10.1 
Hardwar: HPC
Executor: Slurm
Container Engine: Singularity
OS: Linux
pgsc_calc v2.0.0-beta-gccfd636

**Comment by nebfield** [comment]
The [calculator works best with cohort data that have been imputed](https://pgsc-calc.readthedocs.io/en/latest/how-to/samplesheet.html#samplesheet). 

If you have one sample per VCF then you should [merge your target genomes before using the calculator](https://pgsc-calc.readthedocs.io/en/latest/how-to/prepare.html). Multiple rows in a samplesheet are for target genomes that have been split per chromosome.

**Comment by nebfield** [comment]
[WGS data can cause variant matching problems with the current version of the calculator](https://pgsc-calc.readthedocs.io/en/latest/explanation/match.html#are-your-target-genomes-imputed-are-they-wgs). The calculator works best with genotyping array data that have been imputed to increase variant density. 

Some users have been [able to create compatible VCFs from WGS data](https://github.com/PGScatalog/pgsc_calc/discussions/123#discussioncomment-6469422) but this requires some manual work to 1) create gVCFs from BAM files 2) merge gVCFs to create a multi-sample gVCF and 3) include nonvariant sites in the gVCF. 

If you're able to create a multi-sample VCF from the WGS data your samplesheet would look like:

```
sampleset,path_prefix,chrom,format
merged,path/to/merged,,vcf
```

**Comment by nebfield** [comment]
Closing this now. Please feel free to create a new issue or discussion if you have any more questions.
