### ISSUE TITLE
Failed to pull singularity image

### ISSUE THREAD

**Issue by Fiwx** [PGScatalog/pgsc_calc#339]
### Description of the bug

I ran pgsc_calc on the dev branch with this command:

```absolute/path/to/nextflow run pgscatalog/pgsc_calc -profile singularity --input {correct absolute samplesheet path} --pgs_id {a few pgs ids} --target_build {my build, hg37 here} --run_ancestry /path/to/1000G.tar.zst -c -r dev'```

I got the error "Failed to pull singularity image." I was able to replicate this on a different computer after waiting 12 hours. I successfully ran the exact same command last week, also on the dev branch. There was no cache, work dir, etc., since I ran it in an isolated environment that had not had any commands ran in it before this run.

Similar to: https://github.com/PGScatalog/pgsc_calc/issues/327
I will attempt this solution: https://github.com/PGScatalog/pgsc_calc/issues/316

This command works: ```singularity pull oras://registry.forgemia.inra.fr/gafl/singularity/bwa/bwa:latest```
These commands all enter the shell:
```singularity shell https://depot.galaxyproject.org/singularity/plink2:2.00a2.3--h712d239_1```
```singularity shell oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/pgscatalog_utils:amd64-0.3.1```
```singularity shell oras://ghcr.io/pgscatalog/pgscatalog_utils:v0.4.3-singularity```
(and I can run samplesheet_to_json --help from within the shell).

Running the test command on -r dev:
```
Pulling Singularity image oras://ghcr.io/pgscatalog/plink2:2.00a5.10-singularity [cache /absolute/path/to/work/singularity/ghcr.io-pgscatalog-plink2-2.00a5.10-singularity.img]
Pulling Singularity image oras://ghcr.io/pgscatalog/pygscatalog:pgscatalog-utils-1.1.2-singularity [cache /absolute/path/to/work/singularity/ghcr.io-pgscatalog-pygscatalog-pgscatalog-utils-1.1.2-singularity.img]
Pulling Singularity image oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/report:2.00a5 [cache /absolute/path/to/work/singularity/dockerhub.ebi.ac.uk-gdp-public-pgsc_calc-singularity-report-2.00a5.img]
Pulling Singularity image oras://ghcr.io/pgscatalog/pyyaml:6.0-singularity [cache /absolute/path/to/work/singularity/ghcr.io-pgscatalog-pyyaml-6.0-singularity.img]
```

### Command used and terminal output

```console
Jul-14 15:48:49.606 [main] DEBUG nextflow.Session - Session await > all processes finished
Jul-14 15:48:49.606 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-14 15:48:49.606 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Jul-14 15:48:49.625 [Actor Thread 24] ERROR nextflow.Nextflow - ERROR: Projection subworkflow failed
Jul-14 15:48:49.628 [Actor Thread 27] ERROR nextflow.Nextflow - ERROR: Matching subworkflow failed
Jul-14 15:48:49.631 [Actor Thread 26] ERROR nextflow.Nextflow - ERROR: No results report written!
Jul-14 15:48:49.636 [Actor Thread 13] ERROR nextflow.Nextflow - ERROR: No scores calculated!
Jul-14 15:48:49.645 [Actor Thread 25] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
 task: name=PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:RELABEL_SCOREFILES; work-dir=null
 error [java.lang.InterruptedException]: java.lang.InterruptedException
Jul-14 15:48:49.647 [Actor Thread 28] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
 task: name=PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:FRAPOSA_PROJECT; work-dir=null
 error [java.lang.InterruptedException]: java.lang.InterruptedException
Jul-14 15:48:49.649 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
 task: name=PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE; work-dir=null
 error [java.lang.InterruptedException]: java.lang.InterruptedException


[...]

Jul-14 15:48:49.593 [Actor Thread 8] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.IllegalStateException: Failed to pull singularity image
 command: singularity pull --name dockerhub.ebi.ac.uk-gdp-public-pgsc_calc-singularity-zstd-amd64-1.4.8.img.pulling.1720984556971 oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/zstd:amd64-1.4.8 > /dev/null
 status : 143
 hint  : Try and increase singularity.pullTimeout in the config (current is "20m")
 message:
  INFO:  Downloading oras image

[...]

Caused by: java.lang.IllegalStateException: Failed to pull singularity image
 command: singularity pull --name dockerhub.ebi.ac.uk-gdp-public-pgsc_calc-singularity-zstd-amd64-1.4.8.img.pulling.1720984556971 oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/zstd:amd64-1.4.8 > /dev/null
 status : 143
 hint  : Try and increase singularity.pullTimeout in the config (current is "20m")

Version: pgscatalog/pgsc_calc v2.0.0-beta-gcc3a26e
```

### System information

Linux, Singularity
singularity-ce version 4.1.1

**Comment by Fiwx** [comment]
I read [this](https://pgsc-calc.readthedocs.io/en/latest/how-to/offline.html#singularity), and tried these commands:

```
export NXF_SINGULARITY_CACHEDIR=/home/ubuntu/pgsc_calc_singularity_containers
mkdir -p $NXF_SINGULARITY_CACHEDIR

# Extract Singularity image names
git grep 'ext.singularity*' conf/modules.config | cut -f 2 -d '=' | xargs -L 2 echo | tr -d ' ' > singularity_images.txt

# Create a list of local image paths
cat singularity_images.txt | sed 's/oras:\/\///;s/https:\/\///;s/\//-/g;s/$/.img/;s/:/-/' > singularity_image_paths.txt

# Download the Singularity images
paste -d '\n' singularity_image_paths.txt singularity_images.txt | xargs -L 2 sh -c 'singularity pull --disable-cache --dir $NXF_SINGULARITY_CACHEDIR $0 $1'
```
The first three images downloaded very quickly:

- 521.0MiB in essentially 0 seconds
- 58.8MiB in 0 seconds
- 30.1MiB in 0 seconds
- (These may have been cached from an earlier run.)

The fourth image (473.0MiB) is showing a dramatically slower download speed:
- Only 1% complete after some minutes
- Estimated time of 6h55m33s
- Download speed of 19.3 KiB/s
- The download was still progressing but very slowly

I did ^C, then ```rm -rf $NXF_SINGULARITY_CACHEDIR/*``` to try again. Then, I ran: ```paste -d '\n' singularity_image_paths.txt singularity_images.txt | xargs -L 2 sh -c 'singularity pull --disable-cache --dir $NXF_SINGULARITY_CACHEDIR $0 $1'``` and had a similar issue with speed. The first two layers were very fast at ~100 MiB/s, then the third image was slow at 29 KiB/s. I cleared the cachedir again and ran it again, and the third image was downloading around 20 KiB/s.

Perhaps the server hosting this particular image might be having issues. If it was my local network or a temporary issue, I don't see why the same images would be problematic each time.

Here are the images (cat singularity_images.txt):
```
oras://ghcr.io/pgscatalog/pygscatalog:pgscatalog-utils-1.1.2-singularity
oras://ghcr.io/pgscatalog/plink2:2.00a5.10-singularity
oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/zstd:amd64-1.4.8
oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/report:2.00a5
oras://ghcr.io/pgscatalog/pyyaml:6.0-singularity
oras://ghcr.io/pgscatalog/fraposa_pgsc:v0.1.0-singularity
```

It seems like the dockerhub images are problematic but not the ghcr.io images. I cleared $NXF_SINGULARITY_CACHEDIR/* tested each url individually using:
```singularity pull --disable-cache --dir $NXF_SINGULARITY_CACHEDIR {URL here}```

All of the ghcr.io URLs worked, but the dockerhub.ebi.ac.uk URLs did not. The 3rd and 4th URL were downloading at about 16 KiB/s, and all the others were around ~100 MiB/s.

**Comment by nebfield** [comment]
Thanks for the bug report. The EBI GitLab instance has been unstable over the weekend. I can't pull images either 😅 Hopefully the problems will get fixed soon.

I've published the images to the [GitHub container registry](https://github.com/orgs/PGScatalog/packages), and updated the container definitions in the dev branch, so the dev branch should be OK as a workaround.

**Comment by Fiwx** [comment]
Good to know, thank you!
