### ISSUE TITLE
upgrade plink2

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#34]
alpha 3.3 is the new recommended release

https://www.cog-genomics.org/plink/2.0/

**Comment by smlmbrt** [comment]
Yes, this would be helpful for the PCA as well as some of the functions are only stably in that version

**Comment by nebfield** [comment]
now the containers are built and conda is updated, version 1.1 of pgsc_calc will release with plink alpha 3.3

https://github.com/bioconda/bioconda-recipes/pull/36051
