### ISSUE TITLE
Plink - Error invalid chromosome code 

### ISSUE THREAD

**Issue by wbirru** [PGScatalog/pgsc_calc#35]
Hi, I am using this pipeline and encountered the following error:

Error: Invalid chromosome code 'chr1_gl000191_random' on line 9605356 of --vcf
  file.
  (Use --allow-extra-chr to force it to be accepted.)

I have used --allow-extra-chr but the problem persists. I am using an old plink (in the docker container I also upgrade plink 2.0 to 3.3 (module/local/plink2_vcf.nf), however, the problem is still there. 
I have also tried to use --allow-extra-chr in plink2_vcf.nf script again can not avoid the error (where should we apply this flag in the script)
I would like to get quick help as the problem seems easy ---- tried to consult plink page but still could not get a solution.

Thanks

**Comment by smlmbrt** [comment]
Hi @wbirru, currently the pipeline is setup to only run on chr1-22 and sex chromosomes (X,Y, XY) as most of the PGS we see do not contain variants on patches. The easiest way to get the pipeline running would be to remove those variants from your dataset and output a set of pfiles on just those chromosomes, something like:
`plink2 --vcf [yourfile] --allow-extra-chr --chr 1-22, X, Y, XY -make-pgen --out [yourfile]_axy`

**Comment by wbirru** [comment]
Thanks, @smlmbrt for your quick reply. Yes, I understand that your pipeline does calculate only for those chromosomes you mentioned. I will apply your advice.

**Comment by smlmbrt** [comment]
Added to documentation: 
- https://pgsc-calc.readthedocs.io/en/latest/how-to/prepare.html
- https://pgsc-calc.readthedocs.io/en/latest/troubleshooting.html#i-m-having-problems-with-vcf-input
