### ISSUE TITLE
Low match rate

### ISSUE THREAD

**Issue by Links2000** [PGScatalog/pgsc_calc#355]
Hi! Thanks for using the PGS Catalog calculator (`pgsc_calc`). 

If you need help with setting up the calculator, configuration options, or have questions about polygenic risk scores generally, the best place to ask is:
I'm using your tool to calculate PRS scores on UK Biobank but I'm finding that many of the matches such as PGS000010_hmPOS_GRCh37, PGS004861_hmPOS_GRCh37, PGS000010_hmPOS_GRCh37, etc. are well below 0.75, which is quite shocking, theoretically! UKB's genetic data is big enough that it can't cover the variants in these PGSs.
I'm sure they're all genotyped as GRCh37 versions.
I think this is a bit unusual and would like to ask if you have any thoughts on this? I do now QC the genotype data for maf, hwe etc and was wondering if I should remove those QCs.

As well as whether I can just leave out the min_overlap (set to 0?). I am not trying to compare PRS for individual diseases, I am developing further multi-PRS based on these SINGLE PRS, a before and after comparison, do you think it is feasible for me to just ignore min_overlap? Looking forward to your reply and thanks again for your great tools.

* GitHub discussions: https://github.com/PGScatalog/pgsc_calc/discussions

We prefer a public discussion forum instead of answering emails, so other people interested in PGS can find and learn from our discussions.

We also include answers to a lot of questions that get regularly asked in our documentation 
 
* Documentation: https://pgsc-calc.readthedocs.io/en/latest/index.html

**Comment by smlmbrt** [comment]
Will close this as it is redundant with #350 and answer on the discussion thread.
