### ISSUE TITLE
Scores Below Match Threshold Have Zero Reported Matches

### ISSUE THREAD

**Issue by DarioS** [PGScatalog/pgsc_calc#358]
### Description of the bug

In report.html, I have noticed that scores that were previously correctly summarised have zero match values in 2.0.0.

![image](https://github.com/user-attachments/assets/cb624ba6-287c-4fd0-9f33-291f5d085d84)

I don't think these are truly 0% match. Looking at my supplementary table in preparation from late last year which has a subset,

![image](https://github.com/user-attachments/assets/70750155-30c1-4065-b3b0-744902ac2c7d)

Note that some recent scores deposited into the catalogue this year are not in this spreadsheet.

### Command used and terminal output

```console
I have reproduced it a second time by deleting `results` and `work` folders and resubmitting the job.
```

### System information

Nextflow 24.04.1 and H.P.C. and Rocky Linux release 8.10 (Green Obsidian).

**Comment by nebfield** [comment]
Thanks for the bug report! I think this is related to https://github.com/PGScatalog/pygscatalog/pull/42 (which is being released soon) but I will double check
