### ISSUE TITLE
Summary CSV has Multiple Entries

### ISSUE THREAD

**Issue by DarioS** [PGScatalog/pgsc_calc#363]
### Description of the bug

I ran it with EFO ID specified. Many more rows than scores are made. Some scores appear multiple times with different match %.

### Command used and terminal output

```console
-r v2.0.0-beta.3 --trait_efo EFO_0001645
```

### Relevant files

[BioHEART_summary.csv](https://github.com/user-attachments/files/16724855/BioHEART_summary.csv)

### System information

NextFlow 24.04.1 on H.P.C.

**Comment by smlmbrt** [comment]
Hi Dario, this behaviour is expected! The count values split across multiple rows for each row will sum to the number of variants in the scoring file. This log file tells you the counts of variants were match/excluded/unmatched and their characteristics (ambiguous, multi allelic, duplicate, etc). It's described here: https://pgsc-calc.readthedocs.io/en/latest/explanation/output.html#match
