### ISSUE TITLE
Error when running on WGS

### ISSUE THREAD

**Issue by alohasiqi** [PGScatalog/pgsc_calc#374]
### Description of the bug

Hi! 

I have been trying to run the workflow on my WGS samples using singularity on HPC but it keeps throwing out errors. 

Can you help direct me with the right to run the workflow on WGS? I would greatly appreciate your help.

1. I have tested on my vcf file, but it gives some error 

ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF (sle chromosome)'
Error: Missing --chr argument.

the code is
`
nextflow run pgscatalog/pgsc_calc \
    -profile singularity \
    -latest \
    --input code/samplesheet.csv  --target_build GRCh38 \
    --pgs_id PGS000328 \
    --parallel -c code/my_custom.config`

the sampleshee.csv is 
sampleset,path_prefix,chrom,format
sle,mypath/sle, ,vcf

2. when converting the vcf to bfiles, it gives another error
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE (sle)'

the sampleshee.csv is 
sampleset,path_prefix,chrom,format
sle,mypath/sle,22,bfile

**Comment by nebfield** [comment]
Your first samplesheet contains a space in the chromosome row:

```
sle,mypath/sle, ,vcf
```

So the workflow is trying to extract variants from chromosome " " (which doesn't exist). Delete the space and it should be OK.

[WGS data are not yet well supported by the calculator](https://pgsc-calc.readthedocs.io/en/latest/explanation/match.html#are-your-target-genomes-imputed-are-they-wgs), which is probably why you get an error on the `MATCH_COMBINE` step. If you'd like to use the calculator with WGS data it's best to preprocess your VCF to include non-variant sites (the docs have a link).

**Comment by ashenfernando1** [comment]
@nebfield Just wanted to clarify whether supporting WGS natively on `pgsc_calc` is still on the roadmap, because there's a `not planned` tag on this thread, thank you.

**Comment by nebfield** [comment]
Yes, native support for WGS is on the roadmap for the new year 😄

**Comment by smlmbrt** [comment]
Created a placeholder issue: https://github.com/PGScatalog/pgsc_calc/issues/396
