### ISSUE TITLE
VCF Input with JSON sample sheet "input file name collision" error

### ISSUE THREAD

**Issue by robthompsonweb** [PGScatalog/pgsc_calc#375]
### Description of the bug

Following the docs for using [cloud storage](https://pgsc-calc.readthedocs.io/en/dev/how-to/cloud.html#your-genomes-are-in-cloud-storage), it states "If you’re using VCF input, then the VCF path must be repeated for pheno, variants, and geno". 
However when I do this I get the error:

```Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF (1)'

Caused by:
  Process PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF input file name collision -- There are multiple input files for each of the following file names: sample.hg38.g.vcf.gz
```

### Command used and terminal output

`samplesheet.json`

```
[
    {
        "pheno": "s3://bucket-name/sample.hg38.g.vcf.gz",
        "vcf_import_dosage": false,
        "variants": "s3://bucket-name/sample.hg38.g.vcf.gz",
        "geno": "s3://bucket-name/sample.hg38.g.vcf.gz",
        "sampleset": "test",
        "chrom": null,
        "format": "vcf"
    }
]
```

**Comment by nebfield** [comment]
Thanks for the bug report! I think I encountered this problem a few days ago 😅 

Could you try again with the dev branch? You should be able to either clone the repo and check out the dev branch or set `-r dev` in your nextflow command

**Comment by robthompsonweb** [comment]
yes dev branch with fix works 😀
