### ISSUE TITLE
Documentation page does not exist. 

### ISSUE THREAD

**Issue by pjgreer** [PGScatalog/pgsc_calc#38]
Responds with a 404

**Comment by nebfield** [comment]
Thanks for reporting the problem 🙂 Sorry, we migrated from GitHub pages to read the docs, which broke the documentation link. Here's a link that should work:

https://pgsc-calc.readthedocs.io/en/dev/

These docs contain some information that won't be totally accurate until the next pipeline version is released, which should happen in the next week roughly. The new release should fix the documentation link too. I'll keep this issue open until it's sorted.

**Comment by smlmbrt** [comment]
Closed by #51
