### ISSUE TITLE
Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE (cineca chromosome 22 effect type additive 0)'

### ISSUE THREAD

**Issue by Janner125** [PGScatalog/pgsc_calc#387]
### Description of the bug

![image](https://github.com/user-attachments/assets/268e2bfc-f37e-49a6-b25f-fc502820b903)

**Comment by nebfield** [comment]
There's not enough information in the screenshot to diagnose the problem. Could you please include more information, including the command used and all terminal output.

**Comment by Janner125** [comment]
> There's not enough information in the screenshot to diagnose the problem. Could you please include more information, including the command used and all terminal output.

thanks!!!I will put more detail!!!

**Comment by Janner125** [comment]
> There's not enough information in the screenshot to diagnose the problem. Could you please include more information, including the command used and all terminal output.

when I run "nextflow run pgscatalog/pgsc_calc -profile test,conda"
![image](https://github.com/user-attachments/assets/f3284915-42c9-4a13-9cd1-a4c13a3e3493)
![image](https://github.com/user-attachments/assets/e4756d88-0be3-4055-8c02-e78ef2a45276)
![image](https://github.com/user-attachments/assets/29b3829b-a169-4d6e-9e90-3b1378cd7514)

**Comment by nebfield** [comment]
Thanks for the extra information. This is a problem that can happen with the conda profile on some computers.

We're planning to publish a new release this week which should fix the problem. 

If you'd like to test the pre-release to see if it helps you could try:

```
$ nextflow run pgscatalog/pgsc_calc -profile test,conda -r integrate-utils-1.4.1
```

**Comment by Janner125** [comment]
> Thanks for the extra information. This is a problem that can happen with the conda profile on some computers.
> 
> We're planning to publish a new release this week which should fix the problem.
> 
> If you'd like to test the pre-release to see if it helps you could try:
> 
> ```
> $ nextflow run pgscatalog/pgsc_calc -profile test,conda -r integrate-utils-1.4.1
> ```

Thank you!I will try,maybe will fixed.

**Comment by Janner125** [comment]
> Thanks for the extra information. This is a problem that can happen with the conda profile on some computers.
> 
> We're planning to publish a new release this week which should fix the problem.
> 
> If you'd like to test the pre-release to see if it helps you could try:
> 
> ```
> $ nextflow run pgscatalog/pgsc_calc -profile test,conda -r integrate-utils-1.4.1
> ```

![image](https://github.com/user-attachments/assets/74d000d6-a70a-4d0a-92af-332eecbb28b3)
I do  not know what happened!Expect the new version to adapt conda
