### ISSUE TITLE
Consider removing samplesheet requirement in next release

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#42]
Samplesheets make it simpler for us to create input channels for different file formats, for example:

```
[[meta.id, meta.is_vcf: true, meta.chrom: 1], path/to/vcf.gz]
```

But they're annoying for the end user to set up and for us to validate. 

A simpler method might be:

```
--input path/to/*.vcf.gz
```

We could use groovy functions to:

1. Efficiently detect chromosomes
2. Infer format from file extensions or a user parameter

This would give us a chance to add support for compressed plink2 file sets too

**Comment by smlmbrt** [comment]
How would this work with multiple datasets? Would it rely on file naming conventions?

**Comment by nebfield** [comment]
datasets could be grouped by directory name:

```
.
├── dataset1
│   ├── chr1.bed
│   ├── chr1.bim
│   └── chr1.fam
└── dataset2
    ├── chr1.bed
    ├── chr1.bim
    └── chr1.fam
```

**Comment by smlmbrt** [comment]
I think requiring a specific directory structure is less flexible that creating a sample metadata file. We may also need to have sampleset-specific options (see #54; `dosage=DS`) that would be better captured at the naming of the file stage.
