### ISSUE TITLE
Huge amount of Disc Space used 

### ISSUE THREAD

**Issue by wbirru** [PGScatalog/pgsc_calc#43]
Hello, I am only calculating 4 different PGS for 27 samples and the pgsc_calc/work directory is using 76G. If I increase my sample size and PGS number with a big variant size my computer will be filled before even the scores are calculated.

Is there any way that helps us to reduce the number of files created in the "work" directory so that we can avoid filling up the disc quickly?

Cheers

**Comment by smlmbrt** [comment]
This could be that the cache is from old jobs that you're finished with. You can use the [`nextflow clean`](https://www.nextflow.io/docs/latest/cli.html#clean) command to delete files for old jobs. Also the `-resume` flag in nextflow will look for cached versions of the files in the work directory, so can speed up new runs of the pipeline and make use of the same re-labelled genotyping data if you're only changing the scoring files. 

If those things don't solve it: do you know which file are taking up the most space?

**Comment by nebfield** [comment]
The `v1.2.0` release should improve storage usage https://github.com/PGScatalog/pgsc_calc/releases/tag/v1.2.0

Thanks again for reporting the issue!
