### ISSUE TITLE
Interpretation of results

### ISSUE THREAD

**Issue by wbirru** [PGScatalog/pgsc_calc#44]
I have another question as well, regarding the results. I got a nice output for all my samples in aggregated_scores.txt file. I was looking through the documentation to get some info about how w can interpret the results.

I got -ve results for certain PGS and +ve results as well. It is in the range of -2.5XXXXX to 1.9XXXXX. Is there any documentation that can help me understand the results and how to interpret them?

Thanks

**Comment by smlmbrt** [comment]
In the documentation ([dev version](https://pgsc-calc.readthedocs.io/en/dev/output.html#score)) we state: 

> [PGS NAME]_SUM: reports the weighted sum of effect_allele dosages multiplied by their effect_weight for each matched variant in the scoring file. The column name will be different depending on the scores you have chosen to use (e.g. PGS000001_SUM).

We have other features in development that will estimate relative PRS (Z, percentile) based on genetic ancestry.

**Comment by smlmbrt** [comment]
Closed in #51 mentioned here: https://pgsc-calc.readthedocs.io/en/latest/output.html
