### ISSUE TITLE
Use more durable caching for target genomes

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#45]
`-resume` causes some annoying problems when testing lots of different scores on the same target genomes (e.g. resource requirements change across instances)

Use `storeDir` in the work directory for relabelled variants instead, so skipping `-resume` won't waste compute

**Comment by smlmbrt** [comment]
May help address #43

**Comment by nebfield** [comment]
https://github.com/PGScatalog/pgsc_calc/releases/tag/v1.2.0
