### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#5]

**Comment by nebfield** [comment]
* Test resource usage (CPU / mem / time) on different datasets
* Try to automatically set resource usage
* Fix `check_max` or `--max-mem` and `--max-cpu` won't work (currently broken)

**Comment by smlmbrt** [comment]
I have a set of settings that work for UKB (split by chromosome), 1000G, and HGDP. We can add these memory limits, runtimes, and example configs to the documentation.

**Comment by smlmbrt** [comment]
I think UKB sized settings are covered here: https://pgsc-calc.readthedocs.io/en/latest/how-to/bigjob.html
