### ISSUE TITLE
question about dosages

### ISSUE THREAD

**Issue by aheritas** [PGScatalog/pgsc_calc#54]
Hi, congratulations on releasing this tool! This is very useful for the field. I have been testing it and comparing the results to some other methods that also calculate individual PRS scores and I have the following question:

- Currently, I understand that, by default, pgsc_calc calculates individual PRS scores using the hard-called dosages ("GT" field in a VCF). I was wondering if it is possible to calculate the scores using the allelic dosages ("DS" field in a VCF). Either the case this is (or not) a feature you are planning to implement, I would be interested in understanding the rationale behind using GT only.

Thanks again for developing this tool and I am looking forward to implement it in our pipelines in the near future.

**Comment by smlmbrt** [comment]
Thanks for trying out the `pgsc_calc` pipeline! When calculating PGS/PRS with large numbers of variants we've observed very little differences between hard-call genotypes and dosages in the past; however smaller scores and harder to type variants are likely more affected by this (ref: https://doi.org/10.1186/s13073-020-00801-x). 

The current handling of VCFs (in [modules/local/plink2_vcf.nf](https://github.com/PGScatalog/pgsc_calc/blob/main/modules/local/plink2_vcf.nf) uses the default behaviour in plink2 (which is to use GT); however it can be easily adapted to use the dosage field ("DS", instructions: https://www.cog-genomics.org/plink/2.0/input#vcf). We will add this feature in a future release, most likely by adding a column that describes how to extract genotype information from the VCF files as part of the samplesheet. In the meantime line 39 of the module could be edited in a local copy of the repository to be:

`--vcf $vcf dosage=DS \\`

and then re-run using the local copy of the repo using a command like:
`nextflow run pgsc_calc/main.nf -profile <docker/singularity/conda> --input samplesheet.csv --target_build GRCh37 --pgs_id PGS001229`


If you try that let us know how it goes!

**Comment by aheritas** [comment]
Thanks for the reply Sam! I'll be checking the paper and testing your suggestion. Thanks again for developing this tool!

**Comment by aheritas** [comment]
Hi! I tried the suggested modification (--vcf $vcf dosage=DS \\ in line 39) and it works perfectly. Thank you!

**Comment by smlmbrt** [comment]
Excellent! We'll add the ability to specify the `vcf_genotype_field` or something similar to the samplesheet as a column in a future release. That way different samplesets could have genotypes extracted using different fields (e.g. if one is imputed and the other is sequenced).
