### ISSUE TITLE
When selecting traits, add parameter to exclude child traits 

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#55]
The default PGS Catalog view of traits returns child traits, and the API returns child traits by default (@aoifemcm)

Add parameter to exclude child traits and [improve the docs](https://pgsc-calc.readthedocs.io/en/latest/how-to/calculate_pgscatalog.html) to explain this

**Comment by smlmbrt** [comment]
Implemented in utils v0.3 https://github.com/PGScatalog/pgscatalog_utils/commit/2c7216e53ff41334c669f5fa63cf180e1dfbbf27
