### ISSUE TITLE
Handle multiple scoring files

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgsc_calc#6]
Converting multiple score files into a single one with multiple effect columns. This will have to handle variants with different effect alleles and split those into separate files and then further combined later.

**Comment by nebfield** [comment]
- prepare a template for user-submitted scores
- add extra error checking, e.g. maximum one weight per variant

**Comment by nebfield** [comment]
4c964c6b3803f38cd99f54d8f213e943848db839 adds support for multiple scoring files but need to add special handling of recessive / dominant scorefiles

**Comment by nebfield** [comment]
don't specfy score col nums if there's only one score...
```
Command output:
  PLINK v2.00a2.3LM 64-bit Intel (24 Jan 2020)   www.cog-genomics.org/plink/2.0/
  (C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
  Logging to cineca_synthetic_subset_22.log.
  Options in effect:
    --out cineca_synthetic_subset_22
    --pfile cineca_synthetic_subset_22
    --score 22_additive_0.scorefile header-read cols=scoresums
    --score-col-nums 3-3
  
  Start time: Tue Feb 15 11:48:18 2022

Command error:
  Error: Duplicate --score-col-nums parameter '3'.
```

**Comment by nebfield** [comment]
a6e27a353a74d6b586609e2ad4ecc10b014f68fc 540b61b41ce2d11e6a1d2d446c20d38aa6761285 :partying_face:
