### ISSUE TITLE
Previous Version

### ISSUE THREAD

**Issue by aflynncarroll** [PGScatalog/pgsc_calc#62]
./nextflow run pgscatalog/pgsc_calc --help

N E X T F L O W  ~  version 22.10.1
Launching `https://github.com/pgscatalog/pgsc_calc` [high_archimedes] DSL2 - revision: 6f3f04296d [master]

pgscatalog/pgsc_calc v0.1.2dev

Is it possible to get nextflow to run the latest version of pgsc_calc (1.2.0)?

**Comment by smlmbrt** [comment]
You can use the `-r` flag to tell nextflow what branch/tag/commit to run (see [nf pipeline sharing/running docs](https://www.nextflow.io/docs/latest/sharing.html#handling-revisions)). In this case you could run for the stable release: `nextflow run pgscatalog/pgsc_calc -r v1.2.0`

Sometimes you need to add `-latest` to pull the latest revisions if you're using a branch tag (e.g. `main` or `dev`).

**Comment by aflynncarroll** [comment]
That worked. Thanks!
