### ISSUE TITLE
multiple scoring file does not work

### ISSUE THREAD

**Issue by yidingdd** [PGScatalog/pgsc_calc#70]
Hi team, 

I'm trying to compute all pgs from pgs catalogue for 40k individuals in our biobank. 
As a test, I tried to compute the first 10 pgs with the following command:
```{bash}
nextflow run pgscatalog/pgsc_calc \
    -profile docker \
    --input atlas.40k.bfile.csv \
    --scorefile score_file/*.txt.gz \
    --target_build GRCh38 \
    --ref pgsc_calc_ref.sqlar \
    --outdir freeze_40K_pgs \
    --max_cpus 22    \
    --max_memory 352.GB \
    --min_overlap 0 --parallel
```
I met two issues:
1. I expected the pipeline will combine all scores and compute them all at once, but it computed PGS000001 only, although I have PGS000001 - 9 in the score_file folder.
2. it takes 9 mins to compute PGS000001, since the score file only contains 77 SNPs, such a long run time is not expected, it takes much longer than computing pgs directly with plink.

Could you help to figure out potential solutions for the above issues? I uploaded the execution race if it helps.

[execution_trace_2022-12-12_16-05-41.txt](https://github.com/PGScatalog/pgsc_calc/files/10213195/execution_trace_2022-12-12_16-05-41.txt)

Best,
Yi

**Comment by nebfield** [comment]
Hi Yi,

Thanks for reporting the issue.

The `--scorefile` parameter needs to be surrounded by quotes, e.g.: 

```
--scorefile "score_file/*.txt.gz"
```

Using quotes means that nextflow will be able to search for files using your glob pattern (`*.txt.gz`), and multiple scoring files will be staged and combined correctly. 

Without quotes, your shell is probably automatically expanding the path like:

```
--scorefile score_file/PGS000001.txt.gz score_file/PGS000002.txt.gz ...
```

Which will break the workflow.

It's normal that the run time is longer than using plink directly. Most of the work involves relabelling, matching, and logging  variants in scoring files against the variants in your dataset. We use `plink2 --score` internally once we are certain that the scoring files are compatible and match well with your input genomes. 

I hope that makes sense. Please let me know if anything is unclear!

Ben

**Comment by yidingdd** [comment]
Thank you Ben! The multiple score file option works now and it's fast!

Best,
Yi

**Comment by tkamth** [comment]
Hi Ben, I am hitting a related error on this.  When I tried to run multiple scores, some scores fail as expected as it does not match the minimal number of matching variants while others do but still no scores are calculated.  Below is the error message I am seeing, any way around this? 
`Command error:
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001051_hmPOS_GRCh38 fails minimum matching threshold (46.38% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001009_hmPOS_GRCh38 fails minimum matching threshold (69.95% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001003_hmPOS_GRCh38 fails minimum matching threshold (69.20% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001039_hmPOS_GRCh38 fails minimum matching threshold (69.20% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001020_hmPOS_GRCh38 fails minimum matching threshold (69.55% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001041_hmPOS_GRCh38 fails minimum matching threshold (66.10% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001049_hmPOS_GRCh38 fails minimum matching threshold (69.71% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001081_hmPOS_GRCh38 fails minimum matching threshold (66.67% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001064_hmPOS_GRCh38 fails minimum matching threshold (61.21% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001080_hmPOS_GRCh38 fails minimum matching threshold (69.74% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001018_hmPOS_GRCh38 fails minimum matching threshold (67.65% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001034_hmPOS_GRCh38 fails minimum matching threshold (70.08% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001079_hmPOS_GRCh38 fails minimum matching threshold (69.90% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001045_hmPOS_GRCh38 fails minimum matching threshold (40.00% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001014_hmPOS_GRCh38 fails minimum matching threshold (65.22% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001069_hmPOS_GRCh38 fails minimum matching threshold (69.78% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001016_hmPOS_GRCh38 fails minimum matching threshold (70.36% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001094_hmPOS_GRCh38 fails minimum matching threshold (68.54% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001031_hmPOS_GRCh38 fails minimum matching threshold (53.57% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001092_hmPOS_GRCh38 fails minimum matching threshold (64.40% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001044_hmPOS_GRCh38 fails minimum matching threshold (61.73% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001000_hmPOS_GRCh38 fails minimum matching threshold (70.17% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001093_hmPOS_GRCh38 fails minimum matching threshold (70.04% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001076_hmPOS_GRCh38 fails minimum matching threshold (70.85% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001042_hmPOS_GRCh38 fails minimum matching threshold (64.16% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001013_hmPOS_GRCh38 fails minimum matching threshold (52.83% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001095_hmPOS_GRCh38 fails minimum matching threshold (69.13% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 DEBUG    Score PGS001023_hmPOS_GRCh38 passes minimum matching threshold (100.00%  variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001025_hmPOS_GRCh38 fails minimum matching threshold (55.56% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001010_hmPOS_GRCh38 fails minimum matching threshold (71.11% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001011_hmPOS_GRCh38 fails minimum matching threshold (40.00% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001056_hmPOS_GRCh38 fails minimum matching threshold (66.20% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001090_hmPOS_GRCh38 fails minimum matching threshold (70.34% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001021_hmPOS_GRCh38 fails minimum matching threshold (71.18% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001046_hmPOS_GRCh38 fails minimum matching threshold (70.21% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001047_hmPOS_GRCh38 fails minimum matching threshold (68.55% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001071_hmPOS_GRCh38 fails minimum matching threshold (69.40% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001029_hmPOS_GRCh38 fails minimum matching threshold (59.09% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001098_hmPOS_GRCh38 fails minimum matching threshold (67.49% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001043_hmPOS_GRCh38 fails minimum matching threshold (59.42% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001040_hmPOS_GRCh38 fails minimum matching threshold (65.34% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001074_hmPOS_GRCh38 fails minimum matching threshold (68.93% variants match)
  pgscatalog_utils.match.filter: 2022-12-21 09:45:28 ERROR    Score PGS001078_hmPOS_GRCh38 fails minimum matching threshold (69.64% variants match)
  pgscatalog_utils.match.match_variants: 2022-12-21 09:45:28 ERROR    Error: no target variants match any variants in scoring files
  Traceback (most recent call last):
    File "/usr/local/bin/match_variants", line 8, in <module>
      sys.exit(match_variants())
    File "/usr/local/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 73, in match_variants
      raise Exception
  Exception


ERROR: No scores calculated!`

**Comment by smlmbrt** [comment]
> `Command exit status:
> 139

@tkamth Based on this I don't think it's failing because of the variant-match threshold (it should calculate the scores if at least 1 score meets the threshold) as it seems like this code is a `SIGSEGV` (system terminated the container's process to guard against a memory integrity violation). Could you increase the memory allocated to the job and see if the same thing happens?
