### ISSUE TITLE
match variants error

### ISSUE THREAD

**Issue by yidingdd** [PGScatalog/pgsc_calc#71]
Hi team,

Thank you for all your previous help in running the pgsc_calc pipeline! I am able to deploy it in our biobank now.
I am trying to compute all 3000+ pgs scores in our biobank. First, I created bed files that contain snps from all score files. Second, I compute pgs for 100 scores in a batch. 
While most jobs work, some jobs fail due to variant matching errors. The error message is not very informative, so I wish you could provide some directions I can try to debut it. 

Here's the command I used:
```
nextflow run pgscatalog/pgsc_calc \
    -profile docker \
    --input atlas.60k.bfile.csv \
    --scorefile score_file/*.txt.gz \
    --target_build GRCh38 \
    --ref pgsc_calc_ref.sqlar \
    --outdir freeze_60K_pgs \
    --max_cpus 22    \
    --max_memory 352.GB \
    --min_overlap 0 --parallel
```
Here are the errors:
```
#PGS000200_PGS000299, PGS002000_PGS002099, PGS002600_PGS002699
pgscatalog_utils.match.filter: 2022-12-20 20:46:36 DEBUG    Calculating overlap between target genome and scoring file
  .command.sh: line 4:    25 Killed                  combine_matches --dataset ATLAS.60K --scorefile scorefiles.txt.gz --matches *.ipc.zst -n 4 --min_overlap 0 --outdir $PWD --split -v
#PGS000300_PGS000399, PGS002100_PGS002199, PGS002200_PGS002299, PGS002300_PGS002399, PGS002700_PGS002799, PGS003200_PGS003299
pgscatalog_utils.match.label: 2022-12-20 10:55:12 DEBUG    Not excluding flipped matches
  .command.sh: line 4:    27 Killed                  combine_matches --dataset ATLAS.60K --scorefile scorefiles.txt.gz --matches *.ipc.zst -n 4 --min_overlap 0 --outdir $PWD --split -v
#PGS002800_PGS002899
pgscatalog_utils.match.read: 2022-12-20 23:00:43 DEBUG    Reading scorefile
  .command.sh: line 4:    26 Killed                  match_variants --dataset ATLAS.60K --scorefile scorefiles.txt.gz --target ATLAS.60K_6.bim.zst --only_match --chrom 6 --outdir $PWD -n 4 -v
#PGS002900_PGS002999
pgscatalog_utils.match.read: 2022-12-20 23:37:16 DEBUG    Reading scorefile
  .command.sh: line 4:    26 Killed                  match_variants --dataset ATLAS.60K --scorefile scorefiles.txt.gz --target ATLAS.60K_4.bim.zst --only_match --chrom 4 --outdir $PWD -n 4 -v
#PGS003000_PGS003099
pgscatalog_utils.match.read: 2022-12-21 00:09:25 DEBUG    Reading scorefile
  .command.sh: line 4:    26 Killed                  match_variants --dataset ATLAS.60K --scorefile scorefiles.txt.gz --target ATLAS.60K_1.bim.zst --only_match --chrom 1 --outdir $PWD -n 4 -v
#PGS003100_PGS003199
pgscatalog_utils.match.read: 2022-12-21 00:46:45 DEBUG    Reading scorefile
  .command.sh: line 4:    26 Killed                  match_variants --dataset ATLAS.60K --scorefile scorefiles.txt.gz --target ATLAS.60K_9.bim.zst --only_match --chrom 9 --outdir $PWD -n 4 -v

```
Hope you have a great holiday!
Yi

**Comment by smlmbrt** [comment]
Hi @yidingdd, I think those might be killed by the queuing system (e.g. exit statues related to running out of memory or time) and not by the actual python code. Usually the longer error message for the nextflow log for that actual job is more descriptive, as these ones just report where the pipeline stopped by not why.

**Comment by yidingdd** [comment]
Hi Sam,

Which do you refer to by "longer error message for the nextflow log for that actual job"? 
The full command error?
```
Command error:
  root: 2023-02-07 19:06:36 DEBUG    Verbose logging enabled
  pgscatalog_utils.config: 2023-02-07 19:06:36 DEBUG    Using 4 threads to read CSVs
  pgscatalog_utils.config: 2023-02-07 19:06:36 DEBUG    polars threadpool size: 4
  pgscatalog_utils.match.read: 2023-02-07 19:06:36 DEBUG    Reading scorefile
  pgscatalog_utils.match.read: 2023-02-07 19:07:18 DEBUG    --chrom parameter not set, using all variants in scoring file
  pgscatalog_utils.match.preprocess: 2023-02-07 19:07:18 DEBUG    Complementing column effect_allele
  pgscatalog_utils.match.preprocess: 2023-02-07 19:07:18 DEBUG    Complementing column other_allele
  pgscatalog_utils.match.combine_matches: 2023-02-07 19:07:18 DEBUG    Reading matches
  pgscatalog_utils.match.combine_matches: 2023-02-07 19:07:18 DEBUG    Labelling match candidates
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling best match type (refalt > altref > ...)
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling duplicated best match: keeping first instance as best_match = True
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling multiple scoring file lines (accession/row_nr) that best_match to the same variant
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2023-02-07 19:07:18 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Labelling multiallelic matches with exclude flag
  pgscatalog_utils.match.label: 2023-02-07 19:07:18 DEBUG    Not excluding flipped matches
  pgscatalog_utils.match.filter: 2023-02-07 19:13:05 DEBUG    Filtering to best_match variants (with exclude flag = False)
  pgscatalog_utils.match.filter: 2023-02-07 19:13:05 DEBUG    Calculating overlap between target genome and scoring file
  .command.sh: line 4:    29 Killed                  combine_matches --dataset ATLAS.60K --scorefile scorefiles.txt.gz --matches *.ipc.zst -n 4 --min_overlap 0 --outdir $PWD --split -v
```
or the execution trace? 
[execution_trace_2023-02-07_10-46-07.txt](https://github.com/PGScatalog/pgsc_calc/files/10678712/execution_trace_2023-02-07_10-46-07.txt)

Also, based on the execution trace, I think I requested enough memory `--max_cpus 50    --max_memory 80.GB` is enough?

Best,
Yi

**Comment by nebfield** [comment]
Hi Yi,

## Short answer:

Edit the configuration file in `conf/base.config`. Change the `process_medium` label to increase resource requirements:

```
    withLabel:process_medium {
        cpus   = { check_max( 8     * task.attempt, 'cpus'    ) }
        memory = { check_max( 64.GB * task.attempt, 'memory'   ) }
        time   = { check_max( 8.h   * task.attempt, 'time'    ) }
    }

```

The default is 4 CPU / 16GB of RAM. From the logs I can see you're only using 4 CPU, so you're probably only allocating 16GB of RAM.

Once you've saved the file, try rerunning with the parameters `--max_cpus 8 --max_memory 64.GB`. You can change these parameters and resources to whatever you prefer, but we've got the UK Biobank working with roughly 8CPU/64GB RAM before.

## Long answer:

From the execution trace, exit code 137 means the `MATCH_COMBINE` container has run out of RAM and it's been killed by the system (e.g. LSF / SLURM). The workflow would be happy to continue running if it had more RAM.  

In the logs I can see that the threadpool size is 4, but you set `--max_cpus` to 50. So 46 CPUs aren't being used by the process. The same is probably true for the memory you set. To debug the workflow you need to find the working directory of the process that failed.

In the terminal when you run nextflow, each process will have a different hash at the start of each line, for example:

```
[79/fd832e] Cached process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS (cineca_synthetic_subset chromosome 22)
[03/82bc70] Cached process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE (cineca_synthetic_subset)
```

Steps to debug the match_combine process:

1. Find the task hash. In this case, it's `03/82bc70`. It will be different on your computer.
2. Set the directory to `work/03/82bc70...`. There will be extra characters in the path that you need to include. In my example the full path is `work/03/82bc70bcf09bf5bab2da240e426ead/`
3. Check the resources the container had access to by running `grep 'docker run' .command.run`

```    
docker run -i --cpus 2.0 --memory 6144m -e ...
```
In my example you can see that the container is only allocated 2 CPUs and 6GB of RAM, which is the default on the test profile. 

4. Increase the process resources as described in the short answer section

I hope that helps

Ben

**Comment by yidingdd** [comment]
Thank you Ben! It works! Indeed, it only used 4CPUs previously.
A question, what's the relationship between `--max_cpus 50    --max_memory 80.GB` and 
```
    withLabel:process_medium {
        cpus   = { check_max( 8     * task.attempt, 'cpus'    ) }
        memory = { check_max( 64.GB * task.attempt, 'memory'   ) }
        time   = { check_max( 8.h   * task.attempt, 'time'    ) }
    }
```
My understanding is the `withLabel:process_medium` specifies how much resource each task can use, while `--max_cpus` specifies how much resource the whole pipeline can use. Is that correct?

Best,
Yi

**Comment by nebfield** [comment]
Great! We use a lot of the `nf-core` [framework](https://nf-co.re). `--max_cpus` is an `nf-core` parameter. 

`--max_cpus` defines the maximum amount of resources that can be allocated to any process in the workflow. [It doesn't increase the amount of resources each process has available](https://nf-co.re/usage/configuration#max-resources).

Using the default configuration as an example, if `max_cpus == 2` then `process_medium` will be limited to 2 CPU, despite 4 CPU being set in `conf/base.config`. 

`--max_cpus` and `--max_memory` are helpful to prevent a misconfigured workflow from trying to run using huge amounts of resources, which can be expensive on HPCs / the cloud (and it could make your computer crash!).

We'll have to make it clearer in the documentation 😄

**Comment by yidingdd** [comment]
It's very clear to me now! Thank you so much!
