### ISSUE TITLE
Column `n_unmatched` doesn't exist

### ISSUE THREAD

**Issue by lemieuxl** [PGScatalog/pgsc_calc#75]
I think that when there are no unmatched variants, the _rmarkdown_ reports fails.

```bash
nextflow run -resume pgscatalog/pgsc_calc -profile singularity \
    --input ./sample_sheet.csv \
    --pgs_id PGS001033,PGS000777 \
    --target_build GRCh38 \
    --keep_ambiguous
```

All variants from those two PGS should match in my dataset (including one ambiguous marker). This command fails with the following error.

```text
  Quitting from lines 171-191 (report.Rmd) 
  Error in `select()`:
  ! Can't subset columns that don't exist.
  ✖ Column `n_unmatched` doesn't exist.
  Backtrace:
    1. ... %>% ...
    8. dplyr:::select.data.frame(...)
   11. tidyselect::eval_select(expr(c(...)), .data)
   12. tidyselect:::eval_select_impl(...)
   21. tidyselect:::vars_select_eval(...)
       ...
   24. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
   25. tidyselect:::walk_data_tree(new, data_mask, context_mask)
   26. tidyselect:::as_indices_sel_impl(...)
   27. tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
   28. tidyselect:::chr_as_locations(x, vars, call = call)
```

When I remove the `--keep_ambiguous` flag, the pipeline succeeds.

Those are small PGS (PGS000777 has three variants including an ambiguous one, and PGS001033 has only one).

**Comment by nebfield** [comment]
Thanks for the great bug report!

Possibly we didn't consider the edge case of everything working perfectly 👀 

I'll try to reproduce the problem and get back to you.

**Comment by nebfield** [comment]
Fixed in the latest patch release: https://github.com/PGScatalog/pgsc_calc/releases/tag/v1.3.1

Thanks again for your report.

**Comment by lemieuxl** [comment]
Thank you for the quick release (and awesome pipeline)!
