### ISSUE TITLE
terminated with an error exit status (139)

### ISSUE THREAD

**Issue by olatzu** [PGScatalog/pgsc_calc#76]
Hello,

I am new to the PGS catalog. 
I tried to run the first score but I keep on getting the following error: 

PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES terminated with an error exit status (139)

(I have cleared all the memory etc but still I get this)

Thanks a lot in advance for your time and help and constant contribution

**Comment by nebfield** [comment]
Unfortunately It's difficult to understand what's causing the problem from an exit code. Could you please provide some extra details:

* the full nextflow command you ran
* what version of pgsc_calc you're running
* where are you trying to run `pgsc_calc` (e.g. a linux laptop, a MacBook, a HPC cluster...)
* the full output of the workflow run that gets printed

**Comment by smlmbrt** [comment]
Dear @olatzu, it looks like you might have an M1 Mac? Could you add

**Comment by olatzu** [comment]
Dear @smlmbrt  and @nebfield,

Thank you very much for your help. The flag has solved the problem! (when I was setting up the program was also mentioning that the pipeline was set up, but with some errors)- and with adding the flag it look like now everything is ready to go!

Thanks a lot!

**Comment by smlmbrt** [comment]
Glad it was a simple fix!

**Comment by pecko-g** [comment]
Hi there, sorry for opening this again. I'm running into the same error when running the test command.

I've just installed pgsc calc for the first time in a new hpc server and am still testing.


- nextflow command: 
nextflow run pgscatalog/pgsc_calc -profile test,conda

- pgsc version: 
not sure how to check that, I would assume the latest

- I'm running the code on an HPC cluster

- error code:

> executor >  local (3)
> executor >  local (3)
> executor >  local (3)
> [58/dc6cbc] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [ 50%] 1 of 2, failed: 1..
> [31/715593] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCO... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWA... -
> [8e/49aa70] NOTE: Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139) -- Execution is retried (1)
> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   139
> 
> Command output:
>   (empty)
> 
> Command error:
>   OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
> executor >  local (3)
> [58/dc6cbc] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 2 of 2, failed: 2..
> [31/715593] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCO... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWA... -
> [8e/49aa70] NOTE: Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139) -- Execution is retried (1)
> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   139
> 
> Command output:
>   (empty)
> 
> Command error:
>   OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
> executor >  local (3)
> [58/dc6cbc] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 2 of 2, failed: 2..
> [31/715593] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHEC... [100%] 1 of 1 ✔
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPA... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATC... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCOR... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCO... -
> [-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWA... -
> [8e/49aa70] NOTE: Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139) -- Execution is retried (1)
> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (139)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   139
> 
> Command output:
>   (empty)
> 
> Command error:
>   OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
>   OpenBLAS blas_thread_init: RLIMIT_NPROC 256 current, 512 max
>   .command.run: fork: retry: Resource temporarily unavailable
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Assuming input samplesheet is a symlinked file in a nextflow working directory
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Following symlink and attempting to resolve path relative to input file
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Resolving paths relative to: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/assets/examples
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Assuming input samplesheet is a symlinked file in a nextflow working directory
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Following symlink and attempting to resolve path relative to input file
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Resolving paths relative to: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/assets/examples
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Assuming input samplesheet is a symlinked file in a nextflow working directory
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Following symlink and attempting to resolve path relative to input file
>   pgscatalog_utils.samplesheet.check: 2024-01-19 05:24:54 WARNING  Resolving paths relative to: /hpc/users/gomesp04/.nextflow/assets/pgscatalog/pgsc_calc/assets/examples
>   .command.sh: line 2: 102687 Segmentation fault      samplesheet_to_json samplesheet.csv out.json
> 
> Work dir:
>   /hpc/users/gomesp04/work/58/dc6cbc5529e89e3dfc23a460d7de3a
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: Matching subworkflow failed
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: No results report written!
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: No scores calculated!
> 
>  -- Check '.nextflow.log' file for details


Thank you for your help!
