### ISSUE TITLE
Assertion Error in '_check_column_types'

### ISSUE THREAD

**Issue by j0n-a** [PGScatalog/pgsc_calc#79]
I am trying to run pgsc_calc on all of the data from PGS catalog but I get the same error for a number of PGS (PGS002619, PGS000908, PGS002704, PGS002678, etc.). The code has run fully on over 300 other PGSs so I'm not sure what is uniquely wrong with these sets or how to fix it. There are also no details about the assertion error, so it is hard to know where to start.

Any advice would be greatly appreciated.

Here is the code I submit:

nextflow run pgscatalog/pgsc_calc \
-profile singularity \
--input <file_path>/pgsc_calc_samplesheet.csv \
--target_build GRCh38 \
--outdir <output_directory_path> \
--pgs_id PGS002678 \
--min_overlap 0 

Note: the minimum overlap is zero to generate files that I can filter out later if the overlap is too small.

Here is the error:

pgscatalog_utils.match.filter: 2023-01-25 19:20:48 DEBUG    Score PGS002678_hmPOS_GRCh38 passes minimum matching threshold (98.75%  variants match)
  pgscatalog_utils.match.write: 2023-01-25 19:20:48 DEBUG    Checking column types
  Traceback (most recent call last):
    File "/venv/bin/combine_matches", line 8, in <module>
      sys.exit(combine_matches())
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/combine_matches.py", line 36, in combine_matches
      log_and_write(matches=matches, scorefile=scorefile, dataset=dataset, args=args)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 92, in log_and_write
      write_scorefiles(valid_matches, args.split, dataset)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/write.py", line 27, in write_scorefiles
      _check_column_types(matches)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/write.py", line 71, in _check_column_types
      assert col_types == correct_schema
  AssertionError
  INFO:    Cleaning up image...

**Comment by smlmbrt** [comment]
Going to try a couple of these scores on our own datasets and see if I can replicate the error.

**Comment by smlmbrt** [comment]
Going to try a couple of these scores on our own datasets and see if I can replicate the error. Could you let us know the version of the pipeline you're using?

**Comment by j0n-a** [comment]
I am using NetFlow version 22.10.4 and pgsc_calc is version 1.3.0.

**Comment by smlmbrt** [comment]
@j0n-a : I've been able to replicate the bug and will try to figure out what's causing it.

**Comment by j0n-a** [comment]
Thank you for looking into this!

**Comment by smlmbrt** [comment]
@j0n-a the new patch should solve this, try:

**Comment by smlmbrt** [comment]
Hi @j0n-a, if you add the `-latest` flag it should update and run correctly with the new patch (_v1.3.2_):
```
nextflow run pgscatalog/pgsc_calc -latest
-profile singularity 
--input <file_path>/pgsc_calc_samplesheet.csv 
--target_build GRCh38 
--outdir <output_directory_path> 
--pgs_id PGS002678 
--min_overlap 0
```

**Comment by j0n-a** [comment]
Thank You! That solution worked!
