### ISSUE TITLE
Error executing process:MAKE_COMPATIBLE:MATCH_VARIANTS (ThreadPoolBuildError)

### ISSUE THREAD

**Issue by wangbaonan** [PGScatalog/pgsc_calc#82]
Dear team,
when running v1.3.2 i got this error(see below), But the same command I once ran successfully, do you know how to fix it?

`executor >  local (24)
[6a/edf953] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (sample_NGS1926.target.csv) [100%] 1 of 1 ✔
[aa/061485] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                       [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                        -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                       -
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF (XR1103 chromosome 19)        [100%] 22 of 22, stored: 22 ✔
[7c/c3a9ae] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (XR1103 chromosome 21)    [  9%] 2 of 22
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_COMBINE                            -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE                                 -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE                              -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_REPORT                                 -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS                                     -
Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (XR1103 chromosome 12)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (XR1103 chromosome 12)` terminated with an error exit status (1)

Command executed:

  export POLARS_MAX_THREADS=2

  match_variants                  --dataset XR1103         --scorefile scorefiles.txt.gz         --target vcf_XR1103_12.pvar.zst         --only_match         --chrom 12                                    --outdir $PWD         -n 2         -v

  cat <<-END_VERSIONS > versions.yml
  MATCH_VARIANTS:
executor >  local (24)
[6a/edf953] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (sample_NGS1926.target.csv) [100%] 1 of 1 ✔
[aa/061485] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                       [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                        -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                       -
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF (XR1103 chromosome 19)        [100%] 22 of 22, stored: 22 ✔
[1d/6bf04a] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (XR1103 chromosome 12)    [ 13%] 3 of 22, failed: 1
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_COMBINE                            -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE                                 -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE                              -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_REPORT                                 -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS                                     -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (XR1103 chromosome 12)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (XR1103 chromosome 12)` terminated with an error exit status (1)

Command executed:

  export POLARS_MAX_THREADS=2

  match_variants                  --dataset XR1103         --scorefile scorefiles.txt.gz         --target vcf_XR1103_12.pvar.zst         --only_match         --chrom 12                                    --outdir $PWD         -n 2         -v

  cat <<-END_VERSIONS > versions.yml
  MATCH_VARIANTS:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  root: 2023-02-07 11:43:20 DEBUG    Verbose logging enabled
  pgscatalog_utils.config: 2023-02-07 11:43:20 DEBUG    Using 2 threads to read CSVs
  pgscatalog_utils.config: 2023-02-07 11:43:20 DEBUG    polars threadpool size: 2
  pgscatalog_utils.config: 2023-02-07 11:43:20 DEBUG    Temporary directory set up: /tmp/nxf.1TYbJzm8j7/work_match/tmpr3vojk3s
  pgscatalog_utils.match.read: 2023-02-07 11:43:20 DEBUG    Reading scorefile
  pgscatalog_utils.match.read: 2023-02-07 11:43:20 DEBUG    --chrom set, filtering scoring file to chromosome 12
  pgscatalog_utils.match.preprocess: 2023-02-07 11:43:20 DEBUG    Complementing column effect_allele
  pgscatalog_utils.match.preprocess: 2023-02-07 11:43:20 DEBUG    Complementing column other_allele
  pgscatalog_utils.match.match_variants: 2023-02-07 11:43:20 DEBUG    Match mode: single
  pgscatalog_utils.target: 2023-02-07 11:43:20 DEBUG    Scanning header to get file format
  pgscatalog_utils.target: 2023-02-07 11:43:20 ERROR    Can't open target as a text file, so trying to read zstd compressed binary file
  pgscatalog_utils.target: 2023-02-07 11:43:20 DEBUG    Scanning header to get file format
  pgscatalog_utils.target: 2023-02-07 11:43:20 DEBUG    pvar format detected
  pgscatalog_utils.match.read: 2023-02-07 11:43:20 DEBUG    Reading all target data complete
  pgscatalog_utils.target: 2023-02-07 11:43:20 DEBUG    Reading compressed chunks from target genome (slower, lower RAM usage)
  pgscatalog_utils.target: 2023-02-07 11:43:20 DEBUG    Started reading zstd compressed data
  pgscatalog_utils.target: 2023-02-07 11:43:23 DEBUG    5 chunks
  pgscatalog_utils.match.preprocess: 2023-02-07 11:43:23 DEBUG    Filtering target to include chromosomes 1 - 22, X, Y
  thread '<unnamed>' panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:170:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Traceback (most recent call last):
    File "/venv/bin/match_variants", line 8, in <module>
      sys.exit(match_variants())
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 54, in match_variants
      matches: list[list[pl.LazyFrame]] = _fast_match(target_paths, scorefile, low_memory)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 133, in _fast_match
      target: pl.LazyFrame = read_target(paths=target_paths, low_memory=low_memory)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/read.py", line 21, in read_target
      .pipe(annotate_multiallelic)
    File "/venv/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 568, in pipe
      return func(self, *args, **kwargs)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/preprocess.py", line 49, in annotate_multiallelic
      if (df.select('is_multiallelic').unique().collect().get_column('is_multiallelic')).any():
    File "/venv/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 937, in collect
      return pli.wrap_df(ldf.collect())
  pyo3_runtime.PanicException: The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
  pgscatalog_utils.match.tempdir: 2023-02-07 11:43:24 DEBUG    Cleaning up tempdir path <TemporaryDirectory '/tmp/nxf.1TYbJzm8j7/work_match/tmpr3vojk3s'>

Work dir:
  /home/pogadmin/dev_PGP/05_pgsc_calc/17_pgsc_calc_20230207_all/work/1d/6bf04a011d485163725267740a867e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

ERROR: No scores calculated!`

I use **singularity** to run pgsc_calc, My OS is **CentOS 7.9.2009**, The full nextflow command i use :

`nextflow run pgscatalog/pgsc_calc --input sample_NGS1926_Han_2Target.target.csv  -profile singularity --pgs_id PGS001229,PGS001405 --target_build GRCh38 --genotypes_cache cacheGenotypesDir`

I asked this question before, but I didn't see the reply email of github at that time. I'm very sorry！

Best,
Wang

**Comment by smlmbrt** [comment]
Dear @wangbaonan - sorry for not following up on the last ticket (we just assumed it had resolved). Couple of extra questions:
- Does the test command run correctly? Try: `nextflow run pgscatalog/pgsc_calc -profile test,singularity`
- If you try `nextflow run pgscatalog/pgsc_calc --input sample_NGS1926_Han_2Target.target.csv  -profile singularity --pgs_id PGS001229,PGS001405 --target_build GRCh38 --genotypes_cache cacheGenotypesDir -resume` does it resolve? (e.g. is the ThreadPoolBuildError random/intermittent)
- Does it always happen with all inputs, or just a specific set?

**Comment by wangbaonan** [comment]
Dear @smlmbrt 

- `nextflow run pgscatalog/pgsc_calc -profile test,singularity`  ran correctly.
- `nextflow run pgscatalog/pgsc_calc --input sample_NGS1926_Han_2Target.target.csv  -profile singularity --pgs_id PGS001229,PGS001405 --target_build GRCh38 --genotypes_cache cacheGenotypesDir -resume` does not resolve.
- It always happen with all inputs.
- The problem seemed to be solved when I replaced the **singularity** with **docker**, but I don't know the specific reason.

**Comment by smlmbrt** [comment]
Hi @wangbaonan - first off,  I'm glad it works on docker! We also have similar versions of centos on two clusters we use (7 and 8), and singularity works with the pipeline there. 

Our initial thoughts on why singularity does not work while docker does is that it is something to do with how singularity might be setup and communicating with your computer rather than a problem with the actual pipeline. I'm not sure we'll be able to fix the exact problem as we can't replicate it, but please update if you have any additional details.
