### ISSUE TITLE
Create documentation for using pgsc_calc in trusted research environments and computers without internet access

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgsc_calc#9]
Problem with `nf-core download` that seems to affect all pipelines

```

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.2



Specify the name of a nf-core pipeline or a GitHub repository name (user/repo).
? Pipeline name: pgscatalog/pgsc_calc
? Select release / branch: 0.1.2dev  [release]

In addition to the pipeline code, this tool can download software containers.
? Download software container images: singularity

If transferring the downloaded files to another system, it can be convenient to 
have everything compressed in a single file.
This is not recommended when downloading Singularity images, as it can take a 
long time and saves very little space.
? Choose compression type: none
INFO     Saving 'pgscatalog/pgsc_calc'                           download.py:160
          Pipeline revision: '0.1.2dev'                                         
          Pull containers: 'singularity'                                        
          Using $NXF_SINGULARITY_CACHEDIR':                                     
         /home/benjamin/singularity                                             
          Output directory: 'pgscatalog-pgsc_calc-0.1.2dev'                     
INFO     Downloading workflow files from GitHub                  download.py:163
INFO     Downloading centralised configs from GitHub             download.py:167
INFO     Found 1 container                                       download.py:472
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% • 0/1 completed
${ workflow.containerEngine ==  Copying from cache to target directory ━━━━━━━━━
CRITICAL [Errno 2] No such file or directory:                    download.py:182
         '/home/benjamin/singularity/${ workflow.containerEngine                
         == .img'                      
```

**Comment by smlmbrt** [comment]
Add documentation to instruct users how to import/run the pipeline on computers without internet access (e.g. Trusted Research Environments)

**Comment by nebfield** [comment]
It looks like `nf-core download` only supports pulling container images via HTTP (not via native singularity pulling `oras://`)

**Comment by smlmbrt** [comment]
@nebfield does the `nf-core download` work now? Is it worth bringing up with them?

**Comment by nebfield** [comment]
No, I think pulling using the [ORAS protocol](https://oras.land) is probably more complicated to implement than a HTTP download for the nf-core developers.. 

My [feature request](https://github.com/nf-core/tools/issues/2020) hasn't been popular 😅 

Instead I used some [unix utilities to parse and grab the images](https://github.com/PGScatalog/pgsc_calc/blob/cfd8bb606e2023f29a42655620439af0585b5dc0/.github/workflows/ci.yml#L41-L44) to preload container images for the GitHub actions CI workflow.

I included this method in the docs as an example

**Comment by Djeane89** [comment]
Hi, I am new to pgsc_calc.
I have successfully run it in an internet environment using Nextflow and Singularity.
Is there a step-by-step guide (e.g., how to pull or create the container to use in an offline system) for running pgsc_calc in an isolated environment (without internet)?
Thank you :)

**Comment by smlmbrt** [comment]
This doc should help: https://pgsc-calc.readthedocs.io/en/latest/how-to/offline.html

**Comment by Djeane89** [comment]
@smlmbrt , thanks alot, I will try this :)
